add cm3 on home page and hardware datasheet download
radxa-docs/documentation pull request #108
Opened 2023-06-16 03:57 UTC by wallace77777

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
git fetch origin pull/PR_NUMBER/head:PR_BRANCH
git switch PR_BRANCH
yarn start
```

2023-06-21 08:31 UTC, RadxaYuntian commented
编译不通过，先修复一下吧

2023-07-25 11:53 UTC, RadxaYuntian commented
不要merge，可以直接push他的分支

2023-07-26 09:09 UTC, RadxaYuntian requested changes

2023-07-26 09:09 UTC, RadxaYuntian commented on src/css/custom.css
这些css class都是完全重复的，把其中一个改个通用名然后所有用到的都可以用

2023-07-26 09:09 UTC, RadxaYuntian commented on docs/compliance/computer-module/_category_.json
名字是compute module,不是compute**r** module
这两个空文件先删掉

2023-07-26 09:09 UTC, RadxaYuntian commented on docs/compliance/computer-module/cm3.md
删掉

2023-07-26 09:09 UTC, RadxaYuntian commented on docs/compute-module/cm3/cm3-io-board/overview.md
> +
```suggestion
```
删掉无用空行

2023-07-27 03:33 UTC, Maycides commented
@RadxaYuntian 天哥，这个PR先关了吧 我把他的改动cherry pick过来修改了

2023-07-27 06:57 UTC, closed without merging