add fix-freq-guidance for AP6256
radxa-docs/documentation pull request #117
Opened 2023-06-26 12:05 UTC by Ken-Vamrs

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
git fetch origin pull/PR_NUMBER/head:PR_BRANCH
git switch PR_BRANCH
yarn start
```

2023-06-26 12:37 UTC, RadxaYuntian requested changes

2023-06-26 12:37 UTC, RadxaYuntian commented on docs/compliance/fixed-frequency-guidance/pre-env.md
目前的要求是文档写中文，然后在`i18n/en/docusaurus-plugin-content-docs/current/`里面用[DeepL](https://www.deepl.com/translator)生成英文文档

2023-07-07 03:36 UTC, Maycides commented
@Ken-Vamrs 这个英文版放到i18n/en/docusaurus-plugin-content-docs/current/compliance

2023-07-07 03:37 UTC, Maycides commented
这里放中文的

2023-07-11 02:14 UTC, RadxaYuntian commented
没有新提交

2023-07-12 03:24 UTC, RadxaYuntian approved these changes
@Maycides 会完成后续修改

2023-07-12 03:35 UTC, RadxaYuntian requested changes
先block merge，@Maycides 直接在这个的基础上重新开一个pr算了

2023-07-17 08:04 UTC, RadxaYuntian commented
Superseded by #139

2023-07-17 08:04 UTC, closed without merging