Modify a punctuation mark on EN 5B hardware details
radxa-docs/documentation pull request #119
Opened 2023-06-27 09:04 UTC by Maycides

###### Description of changes
全角冒号乱码，更正为半角冒号

###### Review guide

To review this PR locally, please run the following commands:

```bash
git fetch origin pull/PR_NUMBER/head:PR_BRANCH
git switch PR_BRANCH
yarn start
```

2023-06-27 10:45 UTC, Maycides commented
第二个push也被合进来了

2023-06-27 11:56 UTC, RadxaYuntian requested changes

2023-06-27 11:56 UTC, RadxaYuntian commented on docs/rock5/rock5b/getting-started/overview.md
> +- 1x micro SD 卡插槽
microSD是个专有名词，中间没有空格

2023-06-28 02:35 UTC, RadxaYuntian approved these changes

2023-06-28 02:35 UTC, merged