update 3C overview: 4k@60 -> 1920x1080@60
radxa-docs/documentation pull request #130
Opened 2023-06-30 07:21 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head:${PR}
git switch --detach ${PR}
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-06-30 07:31 UTC, RadxaYuntian requested changes

2023-06-30 07:31 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/overview.md
> +ROCK 3C features a quad core Cortex-A55 ARM processor, 32bit 3200Mb/s LPDDR4, up to 1920x1080@60 HDMI, MIPI DSI, MIPI CSI, 3.5mm jack with mic, USB Port, GbE LAN, PCIe 2.0, 40-pin color expansion hea
`up to 1920x1080@60 over HDMI`
中文版是正确的么？

2023-06-30 07:50 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/overview.md
> +ROCK 3C features a quad core Cortex-A55 ARM processor, 32bit 3200Mb/s LPDDR4, up to 1920x1080@60 HDMI, MIPI DSI, MIPI CSI, 3.5mm jack with mic, USB Port, GbE LAN, PCIe 2.0, 40-pin color expansion hea
中文没写分辨率

2023-06-30 08:55 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/overview.md
> +ROCK 3C features a quad core Cortex-A55 ARM processor, 32bit 3200Mb/s LPDDR4, up to 1920x1080@60 HDMI, MIPI DSI, MIPI CSI, 3.5mm jack with mic, USB Port, GbE LAN, PCIe 2.0, 40-pin color expansion hea
那之后需要同步一下。
先把这边的措辞改一下

2023-06-30 10:39 UTC, RadxaYuntian requested changes

2023-07-04 07:01 UTC, RadxaYuntian requested changes

2023-07-04 07:01 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/overview.md
> -ROCK 3C features a quad core Cortex-A55 ARM processor, 32bit 3200Mb/s LPDDR4, up to 1920x1080@60 HDMI, MIPI DSI, MIPI CSI, 3.5mm jack with mic, USB Port, GbE LAN, PCIe 2.0, 40-pin color expansion hea
这一段从中文用DeepL翻译吧

2023-07-04 07:03 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/overview.md
> -ROCK 3C features a quad core Cortex-A55 ARM processor, 32bit 3200Mb/s LPDDR4, up to 1920x1080@60 HDMI, MIPI DSI, MIPI CSI, 3.5mm jack with mic, USB Port, GbE LAN, PCIe 2.0, 40-pin color expansion hea
我改了的呀

2023-07-04 07:04 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/overview.md
> -ROCK 3C features a quad core Cortex-A55 ARM processor, 32bit 3200Mb/s LPDDR4, up to 1920x1080@60 HDMI, MIPI DSI, MIPI CSI, 3.5mm jack with mic, USB Port, GbE LAN, PCIe 2.0, 40-pin color expansion hea
这个提交里[3C EN description update](https://github.com/radxa-docs/documentation/pull/130/commits/ddf25bea0c93c909b748fa2fded85e1ddd359714)

2023-07-04 07:16 UTC, RadxaYuntian approved these changes

2023-07-04 07:16 UTC, merged

2023-07-04 07:20 UTC, RadxaYuntian commented
看了下，[语法角度](https://www.merriam-webster.com/words-at-play/is-it-a-or-an)`a`和`an`其实是由之后单词的发音而不是首字母决定的。S的发音类似ess，所以要用搭配元音的an

2023-07-04 07:22 UTC, Maycides commented
记得最清楚的是小学时候的`an hour`