update ROCK 5B display and 4k camera guide and pics of them
radxa-docs/documentation pull request #137
Opened 2023-07-10 08:23 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head:${PR}
git switch --detach ${PR}
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-07-10 08:28 UTC, RadxaYuntian requested changes
同时需要更新英文版相关说明

2023-07-10 08:28 UTC, RadxaYuntian commented on docs/rock5/rock5b/accessories-guides/camera_4k.md
> +- 重启设备后，你将看到 `/dev/video0` 到 `/dev/video19` 。
我们现在发布的`rbuild`系统统一通过`rsetup`来打开overlay

2023-07-10 08:28 UTC, RadxaYuntian commented on docs/rock5/rock5b/accessories-guides/display_use.md
> +- 启动后，添加一行到文件 `/boot/config.txt` 末尾
rsetup

2023-07-10 08:29 UTC, Maycides commented on docs/rock5/rock5b/accessories-guides/camera_4k.md
> +- 重启设备后，你将看到 `/dev/video0` 到 `/dev/video19` 。
ok 这是之前手动打开的方式吗 是不得重写

2023-07-12 02:08 UTC, Maycides commented on docs/rock5/rock5b/accessories-guides/display_use.md
> +- 启动后，添加一行到文件 `/boot/config.txt` 末尾
已经都改成rsetup了

2023-07-12 03:27 UTC, RadxaYuntian commented
修改好之前不要强推，review的历史都没了

2023-07-12 03:33 UTC, RadxaYuntian requested changes

2023-07-12 03:33 UTC, RadxaYuntian commented on docs/rock5/rock5b/accessories-guides/camera_4k.md
> +- 按下 `Ctrl + Alt + T` 组合键打开终端,运行 `rsetup` 命令：
避免介绍组合键，让用户从Application Launcher里面打开Kconsole

2023-07-12 03:33 UTC, RadxaYuntian commented on docs/rock5/rock5b/accessories-guides/camera_4k.md
> +radxa@rock-5b:~$ rsetup
`rsetup`的具体操作需要引用已有页面，不要重复添加内容

2023-07-12 03:33 UTC, RadxaYuntian commented on docs/rock5/rock5b/accessories-guides/camera_4k.md
> +你可以下载 **cheese** 然后使用以下命令使用摄像机:
既然系统已经有了`gst-launch-1.0`就不用介绍cheese了，而且我感觉你这个命令最后一步是没法执行的

2023-07-12 03:33 UTC, RadxaYuntian commented on docs/rock5/rock5b/accessories-guides/display_use.md
1. 不要介绍组合键
2. 不要重复介绍rsetup

2023-07-12 07:48 UTC, RadxaYuntian approved these changes

2023-07-12 07:49 UTC, merged