add before-start of 3C
radxa-docs/documentation pull request #141
Opened 2023-07-17 11:07 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head:${PR}
git switch --detach ${PR}
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-07-17 11:10 UTC, RadxaYuntian requested changes

2023-07-17 11:10 UTC, RadxaYuntian commented on docs/rock3/rock3c/getting-started/before-start.md
编码不是UTF-8，显示乱码

2023-07-18 02:24 UTC, Maycides commented on docs/rock3/rock3c/getting-started/before-start.md
已修改

2023-07-18 03:32 UTC, RadxaYuntian requested changes
这些修改建议可以在GitHub PR的Files changed页面合并提交

2023-07-18 03:32 UTC, RadxaYuntian commented on docs/rock3/rock3c/getting-started/before-start.md
> +[eMMC 模块](/accessories/emmc_module)，容量大于8GB
```suggestion
microSD 卡，容量不小于 8GB  
[eMMC 模块](/accessories/emmc_module)，容量不小于 8GB  
```

2023-07-18 03:32 UTC, RadxaYuntian commented on docs/rock3/rock3c/getting-started/before-start.md
> +**官方推荐使用[ Radxa Power PD30W](/accessories/pd_30w)。**
```suggestion
:::tip
瑞莎推荐使用 [Radxa Power PD30W](/accessories/pd_30w)。
:::
```

2023-07-18 03:32 UTC, RadxaYuntian commented on docs/rock3/rock3c/getting-started/before-start.md
> +HDMI EDID 显示数据用于确定最佳显示分辨率。在支持 1080p（或 4K）的显示器和电视机上，将选择该分辨率。如果不支持 1080p，则将使用 EDID 报告的下一个可用分辨率。该选定模式适用于大多数显示器/电视机，但并非所有显示器/电视机。
```suggestion
ROCK 3C 最高支持 1920 x 1080 分辨率。
```

2023-07-18 03:32 UTC, RadxaYuntian commented on docs/rock3/rock3c/getting-started/before-start.md
> +将镜像刷写到 micro SD 卡上。
```suggestion
- microSD 读卡器  
将镜像刷写到 microSD 卡上。
```

2023-07-18 03:32 UTC, RadxaYuntian commented on docs/rock3/rock3c/getting-started/before-start.md
> +用于 fastboot/adb 命令和 maskrom 模式通信。
```suggestion
用于 `fastboot`/`adb` 命令和 maskrom 模式通信。
```

2023-07-18 03:32 UTC, RadxaYuntian commented on docs/rock3/rock3c/getting-started/before-start.md
> +以太网电缆用于将ROCK 3连接到本地网络和互联网。
```suggestion
ROCK 3C 支持 Wi-Fi 或以太网连接。 
以太网电缆用于将 ROCK 3C 连接到本地网络和互联网。
```

2023-07-18 03:32 UTC, RadxaYuntian commented on docs/rock3/rock3c/getting-started/before-start.md
> +**官方建议使用[ Radxa Display 8 HD ](/accessories/lcd-8-hd)或[ Radxa Display 10 HD ](/accessories/lcd-10-hd)**。
```suggestion
ROCK 3C 支持 2-lane MIPI DSI 显示功能。 
:::tip
瑞莎建议使用 [Radxa Display 8 HD](/accessories/lcd-8-hd) 或 [Radxa Display 10 HD](/accessories/lcd-10-hd)。
:::
```

2023-07-18 03:32 UTC, RadxaYuntian commented on docs/rock3/rock3c/getting-started/before-start.md
> +最后，将系统存储介质：micro SD 卡或 eMMC 模块插入主板上的插口，并通过 type-C 电源适配器供电启动 ROCK 3C。
```suggestion
最后，将系统存储介质：microSD 卡或 eMMC 模块插入主板上的插口，并通过 Type-C 电源适配器供电启动 ROCK 3C。
```

2023-07-18 06:38 UTC, RadxaYuntian approved these changes

2023-07-18 06:38 UTC, merged