Create ROCK 4 Series and add some information of 4C+ and 4SE
radxa-docs/documentation pull request #144
Opened 2023-07-19 10:22 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-07-20 06:51 UTC, RadxaYuntian requested changes

2023-07-20 06:51 UTC, RadxaYuntian commented on docs/rock4/rock4c+/getting-started/overview.md
>  |CPU|64 位六核处理器<br/>Rockchip RK3399-T<br/>双 1.5GHz Cortex-72 加四 1.0GHz Cortex-A53<br/>Mali T860MP4 gpu，支持 OpenGL ES 1.1/2.0/3.0/3.1/3.2， Vulkan 1.0， Open CL 1.1 1.2， DX11。|
```suggestion
|CPU|64 位六核处理器<br/>Rockchip RK3399-T<br/>双 1.5GHz Cortex-72 加四 1.0GHz Cortex-A53<br/>Mali T860MP4 GPU，支持 OpenGL ES 1.1/2.0/3.0/3.1/3.2， Vulkan 1.0， OpenCL 1.1 1.2， DirectX 11|
```
这种列表可以不要结尾句号

2023-07-20 06:51 UTC, RadxaYuntian commented on docs/rock4/rock4c+/getting-started/overview.md
>  |运行内存|LPDDR4<br/>64 位双通道 3200Mb/s 内存，可选 1GB/2GB/4GB|
```suggestion
|运行内存|LPDDR4 内存，可选 1GB/2GB/4GB|
```

2023-07-20 06:51 UTC, RadxaYuntian commented on docs/rock4/rock4c+/getting-started/overview.md
>  |显示|一个最高支持 1440P@60 的 Micro HDMI 接口<br/>一个最高支持 4k@60 的 Micro HDMI 接口<br/>通过 FPC 连接的 4 通道 MIPI DSI<br/>HDMI 2k、HDMI 4K 和 MIPI DSI 中只有两种可以同时工作。|
```suggestion
|显示|一个最高支持 1440P@60 的 Micro HDMI 接口<br/>一个最高支持 4K@60 的 Micro HDMI 接口<br/>通过 FPC 连接的 4-lane MIPI DSI<br/>HDMI 2K、HDMI 4K 和 MIPI DSI 中只有两种可以同时工作|
```

2023-07-20 06:51 UTC, RadxaYuntian commented on docs/rock4/rock4c+/getting-started/overview.md
> +|存储|eMMC<br/>μSD 卡：最高支持 256 GB|
```suggestion
|存储|eMMC<br/>microSD 卡：最高支持 256 GB|
```

2023-07-20 06:51 UTC, RadxaYuntian commented on docs/rock4/rock4c+/getting-started/overview.md
>  |USB|USB 3.0 OTG X1，位于 USB 3.0 座子的上方，可通过软件配置为 host 或 OTG,<br/>USB 3.0 HOST X1，专用 USB 3.0 通道，位于 USB 3.0 座子的上方<br/>USB 2.0 HOST X2|
```suggestion
|USB|USB 3.0 OTG X1，位于上方的 USB 3.0 插口，可通过软件配置为 Host 或 Peripheral<br/>USB 3.0 X1<br/>USB 2.0 X2|
```

2023-07-20 06:51 UTC, RadxaYuntian commented on docs/rock4/rock4c+/getting-started/overview.md
>  |以太网|千兆以太网网，带以太网供电（PoE），需要额外的 HAT 才能通过 PoE 供电。|
```suggestion
|以太网|千兆以太网<br/>可通过额外选购的 HAT 支持以太网供电（PoE）|
```

2023-07-20 06:51 UTC, RadxaYuntian commented on docs/rock4/rock4c+/getting-started/overview.md
>  |无线连接|802.11 ac wifi，蓝牙 5.0，带外置天线。|
```suggestion
|音频|3.5 毫米插孔，高清编解码器最高支持 24 位/96KHz 音频|
|相机|通过 FPC 连接的双通道 MIPI CSI，支持高达 800 万像素摄像头（0.3mm 间距连接器）|
|无线连接|Wi-Fi 5，蓝牙 5.0，带外置天线|
```

2023-07-20 06:51 UTC, RadxaYuntian commented on docs/rock4/rock4c+/getting-started/overview.md
>  |电源|支持 USB Type-C 5V/3A。|
```suggestion
|电源|支持 USB Type-C 5V/3A|
```

2023-07-20 06:51 UTC, RadxaYuntian commented on docs/rock4/rock4se/getting-started/overview.md
> +|尺寸|85mm x 54mm|
```suggestion
|CPU|64 位六核处理器<br/>Rockchip RK3399-T<br/>双 1.5GHz Cortex-72 加四 1.0GHz Cortex-A53<br/>Mali T860MP4 GPU，支持 OpenGL ES 1.1/2.0/3.0/3.1/3.2， Vulkan 1.0， OpenCL 1.1 1.2， DirectX 11|
|运行内存|LPDDR4 内存，可选 1GB/2GB/4GB|
|存储|eMMC<br/>microSD 卡：最高支持 256 GB<br/>M.2 SSD (M.2 最高支持 2T M2 NVME SSD)|
|显示|标准 HDMI 最高支持 4K@60<br/>通过 FPC 连接的双通道 MIPI DSI<br/>HDMI 和 MIPI DSI 可同时工作|
|音频|3.5 毫米插孔，高清编解码器最高支持 24 位/96KHz 音频|
|相机|通过 FPC 连接的双通道 MIPI CSI，支持高达 800 万像素摄像头（1mm 间距连接器）|
|无线连接|Wi-Fi 5，蓝牙 5.0，带板载或外置天线|
|USB|USB 3.0 OTG X1，位于上方的 USB 3.0 插口，可通过硬件开关配置为 Host 或 Peripheral<br/>USB 3.0 X1<br/>USB 2.0 X2|
|以太网|千兆以太网<br/>可通过额外选购的 HAT 支持以太网供电（PoE）|
|IO|[40 pin GPIO](../hardware/rock4se-gpio)|
|其他|RTC<br/>用于备份时间的 RTC 电池连接器 (选装)|
|电源|USB PD协议：支持 USB Type-C PD 2.0, 9V/2A, 12V/2A<br/>Qualcomm® QC 快充：支持 3.0/2.0 adapter, 9V/2A, 12V/1.5A|
|尺寸|85mm x 54mm|
```

2023-07-20 06:51 UTC, RadxaYuntian commented on docs/rock4/rock4se/hardware/rock4se-gpio.md
编码错误

2023-07-20 07:24 UTC, RadxaYuntian requested changes

2023-07-20 07:24 UTC, RadxaYuntian commented on docs/rock4/alternative-os/_category_.json
> +    "description": "Rock 4 系列现已支持多个第三方操作系统。"
```suggestion
    "description": "ROCK 4 系列现已支持多个第三方操作系统。"
```

2023-07-20 07:24 UTC, RadxaYuntian commented on docs/rock4/official-images.md
> +- **[瑞莎百度云盘](http://rock.sh/rockpi-baidupan)**
这个从2020年开始就没更新了

2023-07-20 07:24 UTC, RadxaYuntian commented on docs/rock4/official-images.md
> +- **[ROCK 4 镜像发布网址](https://github.com/radxa/debos-radxa/releases/latest)** - 最新系统镜像。
这个是旧的链接

2023-07-20 07:24 UTC, RadxaYuntian commented on docs/rock4/alternative-os/third-party-images.md
> +|[![Armbian](/img/third-party-images-pic/Armbian.webp)](https://www.armbian.com/rock-pi-4/)|[Armbian for Rock Pi 4A/B](https://github.com/radxa-build/rockpi-4b/releases/latest)<br/>[Armbian for Rock
1. Rock Pi改成ROCK
2. 我们已经不在编译Armbian镜像了，直接指向Armbian的产品页面（不要指向下载链接，会失效）
3. 最新的Armbian已经是Debian Bookworm和Ubuntu Jammy

2023-07-20 07:24 UTC, RadxaYuntian commented on docs/rock4/alternative-os/third-party-images.md
> +|[![Manjaro](/img/third-party-images-pic/Manjaro-Logo.webp)](https://manjaro.org)|[Manjaro Minimal](https://mirrors.tuna.tsinghua.edu.cn/osdn/storage/g/m/ma/manjaro-arm/rockpi4/minimal/19.06/Manjaro-
指向Manjaro的GitHub下载仓库

2023-07-20 07:24 UTC, RadxaYuntian commented on docs/rock4/alternative-os/third-party-images.md
> +|社区构建镜像|下载|简介或其他说明|
上面比如FreeBSD,OPNsense,Crux也是个人编译的。可能把上面改成“社区支持镜像”，下面改成“个人支持镜像”，来区分最终用户受到支持的程度，然后把上面几个个人编译的也挪下来

2023-07-20 07:24 UTC, RadxaYuntian commented on docs/rock4/official-images.md
> +## 官方镜像
```suggestion
## 官方镜像
```

2023-07-20 07:24 UTC, RadxaYuntian commented on docs/rock4/official-images.md
> +
```suggestion
```
这个放到系统介绍里面

2023-07-20 07:24 UTC, RadxaYuntian commented on docs/rock4/official-images.md
> +||![Debian](/img/Debian-logo.webp)|![Ubuntu](/img/Ubuntu-logo.webp)|![Android](/img/Android-Logo.webp)|![Android TV](/img/Android-tv-logo.webp)|
这么多改成tab吧

2023-07-20 07:24 UTC, RadxaYuntian commented on docs/rock4/products.md
> +|![ROCK 4A/B Plus](/img/rock4/4a+.webp)|ROCK 4A/4B + 采用 OP1（2.0GHz 双核 Cortex-A72 + 1.5Ghz 四核 Cortex-A53 ARM 处理器）、64 位 LPDDR4、最高支持 4K@60 HDMI、MIPI DSI、MIPI CSI、带麦克风的 3.5mm 插孔、USB 端口、GbE LAN、40 pin GPI
particulars link是什么

2023-07-20 07:25 UTC, RadxaYuntian commented
PR的大小还是控制一下

2023-07-20 07:28 UTC, Maycides commented
是创建4系列多了好多东西

2023-07-20 10:33 UTC, RadxaYuntian commented
> 是创建4系列多了好多东西

也可以一次只提交一个产品

2023-07-20 10:36 UTC, RadxaYuntian requested changes

2023-07-20 10:36 UTC, RadxaYuntian commented on docs/rock4/official-images.md
> +|[Debian 11 Desktop(Linux 5.10)](https://github.com/radxa-build/rock-4se/releases)|[Ubuntu 20 Server(Linux 4.4)](https://github.com/radxa-build/rock-4se/releases)|[Android 11 (HDMI 4K)](https://githu
Ubuntu的链接都删了吧

2023-07-20 10:36 UTC, RadxaYuntian commented on docs/rock4/official-images.md
> +|[Debian 11 Desktop(Linux 5.10)](https://github.com/radxa-build/rock-4c-plus/releases)<br/>Please use **radxa/radxa** to log in|[Ubuntu Server 20.04](https://github.com/radxa-build/rock-4c-plus/relea
最新的镜像已经支持rock账号，不用再注明需要用radxa账号了

2023-07-20 10:36 UTC, RadxaYuntian commented on docs/rock4/rock4se/hardware/revisions.md
向这种就可以用一个rock4系列的页面，然后每个产品一个单独的tab

2023-07-21 02:58 UTC, RadxaYuntian requested changes

2023-07-21 02:58 UTC, RadxaYuntian commented on docs/rock4/alternative-os/third-party-images.md
> +|[![Manjaro](/img/third-party-images-pic/Manjaro-Logo.webp)](https://manjaro.org)|[Manjaro (支持 4C 和 4B)](https://github.com/manjaro-arm?q=rock&type=all&language=&sort=)|Manjaro Product.[Install Wiki]
我发你这个是为了告诉你怎么去找，你写文档就直接把链接到每个repo的release页面比如https://github.com/manjaro-arm/rockpi4c-images/releases,不要给用户犯错的机会

2023-07-21 02:58 UTC, RadxaYuntian commented on docs/rock4/alternative-os/third-party-images.md
>  |OS|下载链接|简介|
```suggestion
|社区维护镜像|下载链接|简介|
```

2023-07-21 02:58 UTC, RadxaYuntian commented on docs/rock4/alternative-os/third-party-images.md
> +|个人构建镜像|下载|简介或其他说明|
```suggestion
|个人构建镜像|下载链接|简介|
```
上下保持一致

2023-07-24 07:33 UTC, merged