Update OS-installation guide
radxa-docs/documentation pull request #146
Opened 2023-07-24 08:21 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-07-24 08:40 UTC, RadxaYuntian requested changes

2023-07-24 08:40 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
> +  <TabItem value="micro SD" label="micro SD" default>
```suggestion
  <TabItem value="microSD" label="microSD" default>
```
`microSD`是个专有名词，没有空格

2023-07-24 08:40 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
> +```
```suggestion
:::tip
官方镜像的默认账号/密码为**radxa**/**radxa**。
:::
```

2023-07-24 08:40 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
>  本教程适用于瑞莎所有产品的官方镜像以及部分第三方镜像的烧录安装，目前可用的系统安装途径共有 Micro SD 卡、eMMC、SSD 三种。
```suggestion
本教程适用于瑞莎官方镜像。目前支持的系统安装位置有 microSD 卡、eMMC、及固态硬盘。
```

2023-07-24 08:40 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
>  # 操作系统安装教程
页面标题和sidebar_label尽量保持一致

2023-07-24 08:40 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
```suggestion
![ROCK5A via Win32DiskImager 04](/img/rock5a/rock5a-win32-3.webp)

```
多余空行和结尾空格

2023-07-24 08:40 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
>  ## 安装镜像到 Micro SD Card
这个副标题应该是被tab隐含了，不用再次说明

2023-07-24 08:40 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
>  - 下载[对应产品](../productlist)的官方 Ubuntu / Debian 系统镜像。
```suggestion
- 下载[对应产品](../productlist)的官方系统镜像。
```

2023-07-24 08:40 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
> +  <TabItem value="NVME-SSD" label="NVME SSD">
```suggestion
  <TabItem value="NVMe_SSD" label="固态硬盘">
```
NVMe的e是小写

2023-07-24 08:45 UTC, Maycides commented on docs/general-tutorial/os-installation.md
这里比较神奇 删掉一个空行之后我本地就编不过了

2023-07-24 09:25 UTC, RadxaYuntian commented
你这边如果在github上面已有提交的话，在本地用`git pull --rebase`拉取，就不用merge了

2023-07-24 09:36 UTC, RadxaYuntian requested changes

2023-07-24 09:36 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
> +  <TabItem value="microSD" default>
第一个tab[本身就是默认](https://docusaurus.io/docs/markdown-features/tabs#displaying-a-default-tab)的，所以这里的default其实是多余的

2023-07-24 09:36 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
> +   <TabItem value="eMMC" >
```suggestion
   <TabItem value="eMMC">
```

2023-07-24 09:36 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
> +  <TabItem value="NVMe_SSD">
这里会有下划线显示吧？

2023-07-24 10:04 UTC, Maycides commented on docs/general-tutorial/os-installation.md
> +  <TabItem value="NVMe_SSD">
改回去了 会显示 label 的值

2023-07-24 10:07 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
>  ## 安装镜像到 Micro SD Card
说明一下这里不改的原因

2023-07-25 08:39 UTC, RadxaYuntian requested changes

2023-07-25 08:39 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
多余空格

2023-07-25 08:40 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
空行

2023-07-25 08:47 UTC, RadxaYuntian approved these changes

2023-07-25 10:06 UTC, RadxaYuntian approved these changes

2023-07-25 10:28 UTC, merged