Create Hardware Information of ROCK 4 Series
radxa-docs/documentation pull request #149
Opened 2023-07-25 11:08 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-07-25 11:58 UTC, RadxaYuntian requested changes

2023-07-25 11:58 UTC, RadxaYuntian commented on docs/rock4/hardware/_category_.json
> +	"slug": "/rock4/hardware",
缩进

2023-07-25 11:58 UTC, RadxaYuntian commented on docs/rock4/hardware/_category_.json
> +    "description": "ROCK 4 系列的硬件相关资料信息。"
这个description我好像没看到哪里有显示出来

2023-07-25 11:58 UTC, RadxaYuntian commented on docs/rock4/hardware/download.md
> +  <TabItem value="ROCK 4SE" label="ROCK 4SE">
value不要有空格和特殊符号。只使用字母数字和-_号

2023-07-25 11:58 UTC, RadxaYuntian commented on docs/rock4/hardware/rock4-gpio.md
> +:::
```suggestion
:::caution
并非所有硬件功能都可以同时开启。同一时间，一个引脚只能被分配一个硬件功能。
:::
```

2023-07-26 02:36 UTC, Maycides commented on docs/rock4/hardware/_category_.json
> +    "description": "ROCK 4 系列的硬件相关资料信息。"
很多的description都没显示 显示的其他项目这个位置的信息 没找出来问题出在哪儿

2023-07-26 09:55 UTC, RadxaYuntian approved these changes

2023-07-26 10:02 UTC, merged