Add ROCK 3A Overview
radxa-docs/documentation pull request #156
Opened 2023-07-31 07:22 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-07-31 09:02 UTC, RadxaYuntian requested changes

2023-07-31 09:02 UTC, RadxaYuntian commented on docs/rock3/rock3a/getting-started/overview.md
> +|USB|一个 USB 3.0 OTG, 位于上方的 USB 3.0 端口，通过切换 host/device 来切换硬件功能<br/>一个 USB 3.0 HOST<br/>两个 USB 2.0 HOST|
```suggestion
|USB|一个 USB 3.0 OTG, 位于上方的 USB 3.0 端口，通过硬件开关来切换硬件功能<br/>一个 USB 3.0 HOST<br/>两个 USB 2.0 HOST|
```

2023-07-31 09:02 UTC, RadxaYuntian commented on docs/rock3/rock3a/getting-started/overview.md
> +|以太网|支持以太网供电 (PoE) 的千兆以太网<br/> PoE 供电需要额外的 HAT|
```suggestion
|以太网|支持以太网供电 (PoE) 的千兆以太网<br/>PoE 供电需要额外选购的 HAT|
```

2023-07-31 09:02 UTC, RadxaYuntian commented on docs/rock3/rock3a/getting-started/overview.md
> +|其他|RTC<br/>选装 RTC 电池座子|
这个RTC的连接器是哪些SKU才有？

2023-07-31 09:02 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/_category_.json
> +    "description": "ROCK 3A是一款低成本，高性能的单板计算机 (SBC)。"
英文了

2023-07-31 09:35 UTC, Maycides commented on docs/rock3/rock3a/getting-started/overview.md
> +|其他|RTC<br/>选装 RTC 电池座子|
不清楚 作为一个选择项吧

2023-07-31 09:37 UTC, Maycides commented on docs/rock3/rock3a/getting-started/overview.md
> +最高支持 4K@60 的 HDMI、MIPI DSI、MIPI CSI、带麦克风的 3.5 毫米耳机插孔、USB 端口、千兆以太网、PCIe 3.0、PCIe 2.0、40 pin GPIO 扩展座、PCIe 3.0 和 PCIe 2.0 接口、RTC。
```suggestion
最高支持 4K@60 的 HDMI、MIPI DSI、MIPI CSI、带麦克风的 3.5 毫米耳机插孔、USB 端口、千兆以太网、PCIe 3.0、PCIe 2.0、40 pin GPIO 扩展座、RTC。  
```

2023-07-31 09:37 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/_category_.json
> +    "description": "ROCK 3A是一款低成本，高性能的单板计算机 (SBC)。"
```suggestion
    "description": "The ROCK 3A is a low-cost, high-performance single board computer (SBC)."
```

2023-07-31 10:32 UTC, RadxaYuntian commented on docs/rock3/rock3a/getting-started/overview.md
> +|其他|RTC<br/>选装 RTC 电池座子|
不清楚就要跟生产核对啊。怎么能放错误信息上去呢？

2023-07-31 11:02 UTC, Maycides commented on docs/rock3/rock3a/getting-started/overview.md
> +|其他|RTC<br/>选装 RTC 电池座子|
一直都是选贴 默认不贴 这里要附上贴的SKU吗？

2023-07-31 12:09 UTC, RadxaYuntian commented on docs/rock3/rock3a/getting-started/overview.md
> +|其他|RTC<br/>选装 RTC 电池座子|
带RTC的有能买的现货么

2023-08-01 01:28 UTC, Maycides commented on docs/rock3/rock3a/getting-started/overview.md
> +|其他|RTC<br/>选装 RTC 电池座子|
```suggestion
```

2023-08-01 01:28 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/getting-started/overview.md
> +|Others|RTC<br/>RTC battery connector for time backup(optional)|
```suggestion
```

2023-08-01 02:17 UTC, RadxaYuntian approved these changes

2023-08-01 02:24 UTC, merged