add cm3 compliance
radxa-docs/documentation pull request #165
Opened 2023-08-04 07:24 UTC by wallace77777

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-08-04 07:39 UTC, RadxaYuntian requested changes
正常排版，无需全部加错

2023-08-04 07:44 UTC, wallace77777 commented
加错是什么意思

2023-08-04 08:42 UTC, wallace77777 reviewed
已去除加粗

2023-08-04 08:50 UTC, RadxaYuntian commented on docs/compliance/compute-module/radxa-cm3.md
> +
删去结尾多余空行，只保留一个

2023-08-04 08:50 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/compliance/compute-module/radxa-cm3.md
> +
多余空行

2023-08-04 08:51 UTC, RadxaYuntian commented on docs/compliance/compute-module/radxa-cm3.md
> +## FCC ID
```suggestion
## FCC
```

2023-08-04 08:52 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/compliance/compute-module/radxa-cm3.md
> +## FCC ID
```suggestion
## FCC
```

2023-08-04 11:11 UTC, RadxaYuntian requested changes

2023-08-04 11:11 UTC, RadxaYuntian commented on docs/compliance/compute-module/radxa-cm3.md
> +## FCC ID
没改咋能resolve？要么修改要么给出不改的理由

2023-08-04 11:28 UTC, wallace77777 commented on i18n/en/docusaurus-plugin-content-docs/current/compliance/compute-module/radxa-cm3.md
> +## FCC ID
FCC 有两种认证 FCC ID 和 FCC SDOC。我们的产品有些是做了FCC ID认证，有些做了FCC SDOC认证了。                        
采用FCC ID命名更方便判断产品是否带有无线模块 。
(1)FCC ID: 用于一般无线电产品申请。适用于此方式的设备包括各类短距离、低功率发射器，移动电话，蓝牙设备，WLAN（2.4G,5G）设备等 (2) FCC SDOC 适用于普通不带无线功能的产品，如显示器、普通家用电器、灯具等。包含个人电脑及其周边设备；家用电器设备；电动工具；音视频产品；灯具；玩具；安防类产品等。

2023-08-04 11:39 UTC, wallace77777 commented on docs/compliance/compute-module/radxa-cm3.md
> +## FCC ID
FCC 有两种认证 FCC ID 和 FCC SDOC。我们的产品有些是做了FCC ID认证，有些做了FCC SDOC认证了。
采用FCC ID命名更方便判断产品是否带有无线模块 。
(1)FCC ID: 用于一般无线电产品申请。适用于此方式的设备包括各类短距离、低功率发射器，移动电话，蓝牙设备，WLAN（2.4G,5G）设备等 (2) FCC SDOC 适用于普通不带无线功能的产品，如显示器、普通家用电器、灯具等。包含个人电脑及其周边设备；家用电器设备；电动工具；音视频产品；灯具；玩具；安防类产品等。

2023-08-04 11:39 UTC, wallace77777 commented on i18n/en/docusaurus-plugin-content-docs/current/compliance/compute-module/radxa-cm3.md
> +## FCC ID
FCC 有两种认证 FCC ID 和 FCC SDOC。我们的产品有些是做了FCC ID认证，有些做了FCC SDOC认证了。
采用FCC ID命名更方便判断产品是否带有无线模块 。
(1)FCC ID: 用于一般无线电产品申请。适用于此方式的设备包括各类短距离、低功率发射器，移动电话，蓝牙设备，WLAN（2.4G,5G）设备等 (2) FCC SDOC 适用于普通不带无线功能的产品，如显示器、普通家用电器、灯具等。包含个人电脑及其周边设备；家用电器设备；电动工具；音视频产品；灯具；玩具；安防类产品等。

2023-08-04 11:41 UTC, Maycides approved these changes

2023-08-07 02:25 UTC, RadxaYuntian commented on docs/compliance/compute-module/radxa-cm3.md
> +## FCC ID
给出理由后我要看了没问题才resolve，你不要动那个按钮

2023-08-07 02:25 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/compliance/compute-module/radxa-cm3.md
> +
修改后不需要回复，我自己会去确认

2023-08-07 02:45 UTC, RadxaYuntian approved these changes

2023-08-07 02:52 UTC, merged