update RTSP guide and add EN version
radxa-docs/documentation pull request #168
Opened 2023-08-04 11:12 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-08-04 11:13 UTC, Maycides commented
This PR fixes #166

2023-08-04 11:20 UTC, RadxaYuntian requested changes

2023-08-04 11:20 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp.md
> +你可以参考本指南来使用支持 HDMI-in 的主板进行远程推流用于直播、网课等场景。
```suggestion
# RTSP 远程推流
```
专门把这个改成不限定HDMI IN的通用教程，你又给我改回去了

2023-08-04 11:20 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp.md
> +![VLC-Main](/img/general-tutorial/hdmi-in/VLC-Main.webp)
```suggestion
![VLC-Main](/img/general-tutorial/rtsp/VLC-Main.webp)
```
同时需要修改文件路径

2023-08-07 09:05 UTC, RadxaYuntian requested changes

2023-08-07 09:05 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
> +# RTSP Remote Pushstream Guide
```suggestion
# RTSP Remote Streaming Guide
```

2023-08-07 09:05 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
>  The following is an example of how to watch RSTP video push stream by running [VLC](https://www.videolan.org/vlc/) under Windows.
这个文件是用机器翻译还是人工翻译的？

2023-08-07 09:11 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
>  The following is an example of how to watch RSTP video push stream by running [VLC](https://www.videolan.org/vlc/) under Windows.
机翻的，有的我改了些翻回中文不对劲的地方

2023-08-07 09:15 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
>  The following is an example of how to watch RSTP video push stream by running [VLC](https://www.videolan.org/vlc/) under Windows.
这里RTSP错了哦

2023-08-07 09:17 UTC, Maycides commented on docs/general-tutorial/rtsp.md
>  以下以 Windows 下运行 [VLC](https://www.videolan.org/vlc/) 为例，介绍如何收看 RSTP 视频推流。
```suggestion
以下以 Windows 下运行 [VLC](https://www.videolan.org/vlc/) 为例，介绍如何收看 RTSP 视频推流。
```

2023-08-07 09:17 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
> +The following is an example of how to watch RSTP video push stream by running [VLC](https://www.videolan.org/vlc/) under Windows.
```suggestion
The following is an example of how to watch RTSP video push stream by running [VLC](https://www.videolan.org/vlc/) under Windows.
```

2023-08-07 09:18 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
> +sidebar_label: 'RTSP Remote Pushstream'
```suggestion
sidebar_label: 'RTSP Remote Streaming'
```

2023-08-07 09:25 UTC, RadxaYuntian requested changes

2023-08-07 09:25 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
> +2. Click "Media - Open Network Streaming" to enter the RSTP push stream address.
```suggestion
2. Click "Media - Open Network Streaming" to enter the RSTP stream address.
```

2023-08-07 09:26 UTC, RadxaYuntian requested changes

2023-08-07 09:26 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
> +The following is an example of how to watch RTSP video push stream by running [VLC](https://www.videolan.org/vlc/) under Windows.
```suggestion
The following is an example of how to watch RTSP video stream by running [VLC](https://www.videolan.org/vlc/) under Windows.
```

2023-08-07 09:27 UTC, Maycides reviewed
Modify the description of the error

2023-08-07 09:27 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
> +Starting gst-rtsp-server displays the RSTP link for the current device, but you still need to manually replace `127.0.0.1` with a communicable IP address.
```suggestion
Starting gst-rtsp-server displays the RTSP link for the current device, but you still need to manually replace `127.0.0.1` with a communicable IP address.
```

2023-08-07 09:27 UTC, Maycides commented on docs/general-tutorial/rtsp.md
>  2. 点击 媒体 - 打开网络串流 来输入 RSTP 推流地址
```suggestion
2. 点击 媒体 - 打开网络串流 来输入 RTSP 推流地址
```

2023-08-07 09:27 UTC, Maycides commented on docs/general-tutorial/rtsp.md
>  启动 gst-rtsp-server 后会显示当前设备的 RSTP 链接，但仍需手动将 `127.0.0.1` 替换为可通讯的 IP 地址。
```suggestion
启动 gst-rtsp-server 后会显示当前设备的 RTSP 链接，但仍需手动将 `127.0.0.1` 替换为可通讯的 IP 地址。
```

2023-08-07 09:27 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
> +2. Click "Media - Open Network Streaming" to enter the RSTP push stream address.
```suggestion
2. Click "Media - Open Network Streaming" to enter the RTSP push stream address.
```

2023-08-07 09:39 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
> +2. Click "Media - Open Network Streaming" to enter the RSTP stream address.
```suggestion
2. Click "Media - Open Network Streaming" to enter the RTSP stream address.
```

2023-08-07 10:59 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp.md
> +2. Click "Media - Open Network Streaming" to enter the RSTP stream address.
```suggestion
2. Click "Media - Open Network Streaming" to enter the RTSP stream address.
```

2023-08-07 11:01 UTC, RadxaYuntian approved these changes

2023-08-07 11:09 UTC, merged