Add ROCK 4 Series hardware revision and update hardware information download title
radxa-docs/documentation pull request #176
Opened 2023-08-08 11:09 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-08-08 11:21 UTC, Maycides commented on docs/rock4/hardware/revisions.md
> +sidebar_label: '硬件修订信息'
```suggestion
sidebar_label: '硬件改版信息'
```

2023-08-08 11:21 UTC, Maycides commented on docs/rock4/hardware/revisions.md
> +# 修订详情
```suggestion
# 改版详情
```

2023-08-08 11:21 UTC, Maycides commented on docs/rock4/hardware/revisions.md
> +ROCK 4SE 以前的的乘车名称是 ROCK Pi B。
```suggestion
ROCK 4SE 以前的的名称是 ROCK Pi B。
```

2023-08-09 03:28 UTC, RadxaYuntian requested changes

2023-08-09 03:28 UTC, RadxaYuntian commented on docs/rock4/hardware/revisions.md
> +ROCK 4SE 以前的的名称是 ROCK Pi B。
ROCK 4SE 和 ROCK 4B 是两个不同的产品吧，之前ROCK 4B的版本历史就不要放过来

2023-08-09 03:28 UTC, RadxaYuntian commented on docs/rock4/hardware/revisions.md
> +- **V1.73:**
```suggestion
- **V1.73:**  
```
产品的历史从第一版开始，跟他之前基于的产品无关
硬件功能差异应该在产品介绍里面说明，不是在产品修改历史里面

2023-08-09 03:28 UTC, RadxaYuntian commented on docs/rock4/hardware/revisions.md
> +- **V1.5:**
```suggestion
- **V1.5:**  
```

2023-08-09 03:28 UTC, RadxaYuntian commented on docs/rock4/hardware/revisions.md
> +- **V1.2:**
```suggestion
- **V1.2:**  
```
产品生产状态应该在介绍页里面说明

2023-08-09 06:37 UTC, Maycides commented on docs/rock4/hardware/revisions.md
> +ROCK 4SE 以前的的名称是 ROCK Pi B。
前面的版本删了

2023-08-09 08:09 UTC, RadxaYuntian requested changes

2023-08-09 08:09 UTC, RadxaYuntian commented on docs/rock4/hardware/revisions.md
> +- **V1.53:**
ROCK 4SE现在有新版本么？如果只生产了v1.53没有别的版本，那就是没有改版

2023-08-09 08:09 UTC, RadxaYuntian commented on docs/rock4/hardware/revisions.md
> +- **V1.2:**
版本顺序和别的相反，把最新的放到最上

2023-08-09 08:28 UTC, Maycides commented on docs/rock4/hardware/revisions.md
> +- **V1.53:**
ok 我先确认下生产信息

2023-08-09 08:48 UTC, Maycides commented on docs/rock4/hardware/revisions.md
> +- **V1.53:**
仅生产过V1.53，已更新描述

2023-08-09 11:33 UTC, RadxaYuntian requested changes

2023-08-09 11:33 UTC, RadxaYuntian commented on docs/rock4/hardware/revisions.md
> +首个生产版本，暂无硬件更新。
```suggestion
初始版本。
```

2023-08-09 11:33 UTC, RadxaYuntian commented on docs/rock4/hardware/revisions.md
> +板载 Wifi 天线。
```suggestion
板载 Wi-Fi 天线。
```

2023-08-09 11:33 UTC, RadxaYuntian commented on docs/rock4/hardware/revisions.md
> +增加外置 Wifi 天线选项，默认不焊接。
```suggestion
增加外置 Wi-Fi 天线选项。  
```

2023-08-09 11:33 UTC, RadxaYuntian commented on docs/rock4/hardware/revisions.md
> +更改耳机检测电路，默认使用 HP 插孔中的麦克风。
```suggestion
更改耳机检测电路，默认使用耳机插孔中的麦克风。  
```

2023-08-09 11:33 UTC, RadxaYuntian commented on docs/rock4/hardware/revisions.md
> +![ROCK 4C+ Button](/img/rock4/rock4b+-button.webp)
```suggestion
初始版本。
```

2023-08-10 02:50 UTC, RadxaYuntian approved these changes

2023-08-10 02:57 UTC, merged