new add rock5b power
radxa-docs/documentation pull request #182
Opened 2023-08-14 07:19 UTC by wallace77777

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-08-14 08:24 UTC, RadxaYuntian commented
改了一下。@wallace77777 @Maycides @xzuoqi 麻烦审核一下

2023-08-14 08:25 UTC, RadxaYuntian requested changes

2023-08-14 08:46 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/getting-started/power.md
> +When the ROCK 5B is connected to the power supply, the green power LED will stay on. Press the power button to start the system.
```suggestion
When the ROCK 5B is connected to the power supply and it's shut down, the green power LED will stay on. Press the power button to start the system.
```

2023-08-14 09:18 UTC, wallace77777 commented
> 改了一下。@wallace77777 @Maycides @xzuoqi 麻烦

2023-08-14 09:23 UTC, RadxaYuntian requested changes

2023-08-14 09:23 UTC, RadxaYuntian commented on docs/rock5/rock5b/getting-started/power.md
> +当 ROCK 5B 接上电源之后，电源绿灯将会一直常亮。按下电源键即可启动。
```suggestion
当 ROCK 5B 接上电源之后，在关机状态下电源绿灯将会一直常亮。此时按下电源键即可启动。
```

2023-08-15 08:02 UTC, RadxaYuntian commented
@wallace77777 @Maycides @xzuoqi 没问题的话在 Files changed 里面approve一下

2023-08-15 08:09 UTC, Maycides approved these changes

2023-08-15 08:57 UTC, RadxaYuntian approved these changes

2023-08-15 09:05 UTC, merged