new add rock4se power
radxa-docs/documentation pull request #183
Opened 2023-08-15 10:44 UTC by wallace77777

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-08-15 11:40 UTC, RadxaYuntian commented
我是觉得这些包括之前5B的，都可以删掉，只要确保产品介绍里有标注电源键就行。

这些看上去都是很常规的东西

2023-08-16 02:43 UTC, wallace77777 commented
我同意你的建议，重复且常规的内容确实没太必要。
个人目前想法是先上传，以免纯小白不清楚。
后期我在写外设介绍的时候或者其他文档内容再把电源管理再添加上去，然后再把这篇删除即可。

2023-08-16 02:43 UTC, wallace77777 commented
> 我是觉得这些包括之前5B的，都可以删掉，只要确保产品介绍里有标注电源键就行。
> 
> 这些看上去都是很常规的东西



> 我是觉得这些包括之前5B的，都可以删掉，只要确保产品介绍里有标注电源键就行。
> 
> 这些看上去都是很常规的东西

我同意你的建议，重复且常规的内容确实没太必要。
个人目前想法是先上传，以免纯小白不清楚。
后期我在写外设介绍的时候或者其他文档内容再把电源管理再添加上去，然后再把这篇删除即可。

2023-08-16 08:45 UTC, RadxaYuntian commented
有不相关的内容可以开一个新的分支提交，你这样PR越来越大审不过来的。
可以问问 @Maycides 怎么操作

2023-08-16 09:09 UTC, RadxaYuntian requested changes

2023-08-16 09:09 UTC, RadxaYuntian commented on docs/rock4/rock4a/_category_.json
既然是4A和4B那么路径应该叫rock4ab

2023-08-17 08:43 UTC, RadxaYuntian requested changes
英文部分也需要类似修改，具体就不写了

2023-08-17 08:43 UTC, RadxaYuntian commented on docs/rock4/rock4ab/getting-started/_category_.json
> +        "slug": "/rock4/rock4a/getting-started",
```suggestion
        "slug": "/rock4/rock4ab/getting-started",
```

2023-08-17 08:43 UTC, RadxaYuntian commented on docs/rock4/rock4ab/getting-started/overview.md
> +![4C+ close view](/img/rock4/4a/rock4a.webp)
```suggestion
![4A close view](/img/rock4/4a/rock4a.webp)  
```

2023-08-17 08:43 UTC, RadxaYuntian commented on docs/rock4/rock4ab/getting-started/overview.md
> +ROCK 4A 与 ROCK 4B 的区别是 ROCK 4A 搭载板载无线模块（Wifi&BT），ROCK 4B 不搭载板载模块，其他参数均一样。
```suggestion
ROCK 4B 相比于 ROCK 4A 额外搭载了板载无线模块，同时支持 PoE 供电（需额外选配 PoE HAT）。
```

2023-08-17 08:43 UTC, RadxaYuntian commented on docs/rock4/rock4ab/getting-started/overview.md
> +|    CPU    |              Rockchip RK3399, 64 位六核处理器<br/>双核 1.8GHz Cortex-72 加四核 1.4GHz Cortex-A53              |
```suggestion
|    CPU    |              Rockchip RK3399，64 位六核处理器<br/>双核 1.8GHz Cortex-72<br/>四核 1.4GHz Cortex-A53              |
```

2023-08-17 08:43 UTC, RadxaYuntian commented on docs/rock4/rock4ab/getting-started/overview.md
> +| 运行内存  |                                           LPDDR4 内存，可选 2GB/4GB                                           |
```suggestion
| 内存  |                                           LPDDR4 内存，可选 2GB/4GB                                           |
```

2023-08-17 08:43 UTC, RadxaYuntian commented on docs/rock4/rock4ab/getting-started/overview.md
> +|   存储    |                eMMC<br/>microSD 卡：最高支持 256 GB<br/>M.2 SSD (M.2 最高支持 2T M2 NVME SSD)                 |
```suggestion
|   存储    |                eMMC<br/>microSD<br/>M.2 NVMe 固态硬盘                 |
```

2023-08-17 08:43 UTC, RadxaYuntian commented on docs/rock4/rock4ab/getting-started/overview.md
> +|  以太网   |                           千兆以太网<br/>可通过额外选购的 HAT 支持以太网供电（PoE）                           |
```suggestion
|  以太网   |                           千兆以太网<br/>ROCK 4B 可通过额外选购的 HAT 支持以太网供电（PoE）                           |
```

2023-08-17 08:43 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/rock4/rock4ab/getting-started/_category_.json
> +    "slug": "/rock4/rock4a/getting-started",
```suggestion
    "slug": "/rock4/rock4ab/getting-started",
```

2023-08-17 10:37 UTC, RadxaYuntian commented
你可以直接在 https://github.com/radxa-docs/documentation/pull/183/files 批量选择修改建议，然后一次性提交

2023-08-17 10:38 UTC, RadxaYuntian approved these changes

2023-08-17 10:44 UTC, merged