Add 8HD lcd usage guide
radxa-docs/documentation pull request #192
Opened 2023-08-23 03:05 UTC by Maycides

###### Description of changes
需要在 3C 5.10 内核软件支持 8 寸屏后合入。
This PR fixes issue #189 

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-08-23 03:10 UTC, RadxaYuntian commented
然而不是还没支持么？先把这个pr改成draft

2023-08-23 03:22 UTC, RadxaYuntian requested changes

2023-08-23 03:22 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-product.md
> +GT911 支持最多 5 点并发触控，实时追踪准确位置和运动轨迹以及触控区域。 此外，它还可以根据需要向主机报告这些信息。
结尾只有一个空格，意义不明确

2023-08-23 03:22 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-product.md
> +这款 8.0 英寸显示屏可让您创建交互式项目，例如平板电脑、工业 HMI、信息仪表板等。 Radxa Display 8 HD 具有用于电源、显示和触摸的单根电缆以及启用的软件屏幕键盘，无需连接键盘或鼠标即可为您提供完整的人机界面。
结尾只有一个空格，意义不明确

2023-08-23 03:22 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-product.md
> +- 内置电容式感应电路和高性能 MPU
列表结尾不需要双空格，会自动换行

2023-08-23 03:22 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +[Radxa Display 8 HD](lcd-8-hd-product) 显示面板现已支持以下瑞莎产品，后续会逐步适配更多主板：
```suggestion
[Radxa Display 8 HD](lcd-8-hd-product) 显示面板现已支持以下瑞莎产品：  
```
文档里不要为未来许诺

2023-08-23 03:22 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +其中，15 pin 转 40 pin 的 FPC 排线有一个需要额外连接的 7 pin 座子，其定义如下：
```suggestion
其中，15 pin 转 40 pin 的 FPC 排线有需要额外连接的 7 pin 排针，其定义如下：
```
避免`座子`这种普通人不熟悉的术语

2023-08-23 03:22 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +:::note 提示
```suggestion
:::note
```
语法上后面不需要额外的字段

2023-08-23 03:22 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +此处以 ROCK 5A 为演示对象，其他主板操作方式类似。
```suggestion
此处以 ROCK 5A 为演示对象，其他产品操作方式类似。
```
包括后文，使用`产品`而不是`主板`。

2023-08-23 03:22 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +:::tip 提示
```suggestion
:::tip
```

2023-08-23 03:22 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +推荐使用瑞莎官方 30W 适配器：[**瑞莎 PD 30W 适配器**](/accessories/pd_30w)。
```suggestion
推荐使用[瑞莎 PD 30W 适配器](/accessories/pd_30w)。
```
1. 避免重复文字
2. 不要无意义的加粗

2023-09-12 02:11 UTC, Maycides commented
天哥 这个PR可以合了

2023-09-12 02:53 UTC, RadxaYuntian commented
先修复冲突

2023-09-12 03:32 UTC, RadxaYuntian commented
看这里两行怎么修复和自动检测：https://github.com/radxa-docs/documentation/actions/runs/6154544720/job/16700065962?pr=192#step:3:636

2023-09-12 08:00 UTC, RadxaYuntian requested changes

2023-09-12 08:00 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +   ![ROCK 5A-Radxa Display 8 HD](/img/accessories/rock5a-connect-fpc.webp)
```suggestion
   其中，40 pin 一端接到显示面板上：向上拨起 FPC 接头黑色卡扣，将 FPC 排线插入连接器，然后按下黑色卡扣固定 FPC 排线  
   ![Radxa Display 8 HD](/img/accessories/8hd-connect-fpc.webp)  
   39 pin 一端接到产品 DSI 连接器上：向上拨起 FPC 接头黑色卡扣，将 FPC 排线插入连接器，然后按下黑色卡扣固定 FPC 排线  
   ![ROCK 5A-Radxa Display 8 HD](/img/accessories/rock5a-connect-fpc.webp)
```

2023-09-12 08:00 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +Step 3：将卡扣向下按紧，固定排线
```suggestion
15 pin 端子接到产品 DSI 连接器上：  
Step 1：将座子白色卡扣向上拨起  
Step 2：排线金手指背对白色卡扣插入连接器  
Step 3：将卡扣向下按紧，固定排线  
```

2023-09-12 08:00 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +3. 排线接线 pin 脚通过杜邦线接到产品 GPIO 座子上，接法如下：
```suggestion
3. 通过杜邦线连接额外接口，接法如下：
```

2023-09-12 08:00 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +| FPC 线 pin 脚 |      |          产品 GPIO pin 脚           |
```suggestion
| FPC 线引脚 |      |          单板机 GPIO 引脚           |
```

2023-09-12 08:28 UTC, RadxaYuntian requested changes
还是重新机器翻译一遍英文吧

2023-09-12 08:46 UTC, RadxaYuntian requested changes

2023-09-12 08:46 UTC, RadxaYuntian commented on docs/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +Step 1：将座子白色卡扣向上拨起
```suggestion
Step 1：将连接器白色卡扣向上拨起  
```

2023-09-12 08:46 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/accessories/lcd-8-hd/lcd-8-hd-usage.md
> +Step 1: Pivot the white tab of the seat upwards
```suggestion
Step 1: lift up the white tab on the FPC connector  
```

2023-09-12 08:54 UTC, RadxaYuntian approved these changes

2023-09-12 09:03 UTC, merged