add FFmpeg tutorial
radxa-docs/documentation pull request #193
Opened 2023-08-23 09:07 UTC by CodeChenL

关联#191 
先review一下，没问题的话，我再添加英文页面

2023-08-24 06:46 UTC, RadxaYuntian requested changes

2023-08-24 06:46 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp-gstreamer.md
> +使用 HDMI RX 时，目前 gst-mppenc 暂不支持 NV24(YCbCr444) 与 BGR 输入，需要 HDMI 输入端切换颜色格式为 NV12(YCbCr420) 或 NV16(YCbCr422)，或者使用 [FFMpeg](./rtsp-ffmpeg) 进行推流。
```suggestion
使用 HDMI RX 时，目前 gst-mppenc 暂不支持 NV24(YCbCr444) 与 RGB 输入，需要 HDMI 输入端切换颜色格式为 NV12(YCbCr420) 或 NV16(YCbCr422)，或者使用 [FFMpeg](./rtsp-ffmpeg) 进行推流。
```

2023-08-24 06:46 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp-ffmpeg.md
> +sudo apt install librockchip-mpp-dev librockchip-vpu0 librga-dev libyuv-dev libdrm-dev pkg-config libx264-dev build-essential git
```suggestion
sudo apt install librockchip-mpp-dev librockchip-vpu0 librga-dev libyuv-dev libdrm-dev pkg-config libx264-dev build-essential git cmake
```

2023-08-24 06:46 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp-ffmpeg.md
> +cmake -DRKPLATFORM=ON -DHAVE_DRM=ON && make
```suggestion
cmake -DRKPLATFORM=ON -DHAVE_DRM=ON && make -j$(nproc)
```

2023-08-24 06:46 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp-ffmpeg.md
> +make -j8
```suggestion
make -j$(nproc)
```

2023-08-24 06:46 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp-ffmpeg.md
> +### 获取最新 MPP 源码并编译
```suggestion
### 编译并安装最新 MPP
```

2023-08-24 06:46 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp-ffmpeg.md
> +cd FFmpeg/
```suggestion
### 编译并安装 FFmpeg

```bash
git clone https://github.com/hbiyik/FFmpeg.git
pushd FFmpeg/
```

2023-08-24 06:46 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp-ffmpeg.md
> +cd mpp
```suggestion
pushd mpp
```

2023-08-24 06:46 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp-ffmpeg.md
> +sudo cp ./mpp/legacy/librockchip_vpu.so* /lib/aarch64-linux-gnu
```suggestion
sudo cp ./mpp/legacy/librockchip_vpu.so* /lib/aarch64-linux-gnu
popd
```

2023-08-24 06:46 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp-ffmpeg.md
> +sudo make install
```suggestion
sudo make install
popd
```

2023-08-24 06:46 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp-ffmpeg.md
> +需将 FFmpeg 命令最后的RTSP链接中的 `0.0.0.0` 替换为可通讯的 IP 地址。
```suggestion
需使用可通讯的 IP 地址。
```
ffmpeg最后那个是绑定接口和端口，0.0.0.0意味着绑定到所有接口，所以这里只需要使用任意一个能连接的ip即可

2023-08-24 10:37 UTC, RadxaYuntian commented
英文的也添加一下吧

2023-08-24 11:00 UTC, CodeChenL commented
> 英文的也添加一下吧

嗯，有空我加一下

2023-08-26 10:11 UTC, CodeChenL commented
已翻译

2023-08-28 02:30 UTC, RadxaYuntian requested changes

2023-08-28 02:30 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp-ffmpeg.md
> +sidebar_label: 'RTSP Remote Streaming Guide(based on FFmpeg)'
```suggestion
sidebar_label: 'RTSP Remote Streaming Guide (based on FFmpeg)'
```

2023-08-28 02:30 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp-ffmpeg.md
> +# RTSP Remote Streaming Guide(based on FFmpeg)
```suggestion
# RTSP Remote Streaming Guide (based on FFmpeg)
```

2023-08-28 02:30 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp-gstreamer.md
> +sidebar_label: 'RTSP Remote Streaming(based on Gstreamer)'
```suggestion
sidebar_label: 'RTSP Remote Streaming (based on Gstreamer)'
```

2023-08-28 02:30 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp-gstreamer.md
> +# RTSP Remote Streaming Guide(based on Gstreamer)
```suggestion
# RTSP Remote Streaming Guide (based on Gstreamer)
```

2023-08-28 02:30 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp-gstreamer.md
> +When using HDMI RX, gst-mppenc does not support NV24(YCbCr444) and RBG inputs currently, you need to switch the colour format of HDMI input to NV12(YCbCr420) or NV16(YCbCr422), or use [FFMpeg](./rtsp
```suggestion
When using HDMI RX, gst-mppenc does not support NV24(YCbCr444) and RBG inputs currently, you need to switch the colour format of HDMI input to NV12(YCbCr420) or NV16(YCbCr422), or use [FFMpeg](./rtsp-ffmpeg) for streaming.
```

2023-08-28 02:30 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp-ffmpeg.md
> +Input sources with lower than 720P resolution may cause encoding failure when using HDMI RX
```suggestion
Input sources with lower than 720P resolution may cause encoding failure when using HDMI RX.
```

2023-08-28 02:30 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp-ffmpeg.md
> +Here we assume that `/dev/video0` is the video source you want to use. If your camera is assigned a different name, replace the corresponding filename in the following command line.
```suggestion
Here we assume that `/dev/video0` is the video source you want to use. If your camera is assigned to a different name, replace the corresponding device name in the following command line.
```

2023-08-28 02:32 UTC, RadxaYuntian requested changes

2023-08-28 02:32 UTC, RadxaYuntian commented on docs/general-tutorial/rtsp-gstreamer.md
> +使用 HDMI RX 时，目前 gst-mppenc 暂不支持 NV24(YCbCr444) 与 RGB 输入，需要 HDMI 输入端切换颜色格式为 NV12(YCbCr420) 或 NV16(YCbCr422)，或者使用 [FFMpeg](./rtsp-ffmpeg) 进行推流。
```suggestion
使用 HDMI RX 时，目前 gst-mppenc 暂不支持 NV24(YCbCr444) 与 RGB 输入，需要 HDMI 输入端切换颜色格式为 NV12(YCbCr420) 或 NV16(YCbCr422)，或者使用 [FFmpeg](./rtsp-ffmpeg) 进行推流。
```

2023-08-28 02:32 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/rtsp-gstreamer.md
> +When using HDMI RX, gst-mppenc does not support NV24(YCbCr444) and RBG inputs currently, you need to switch the colour format of HDMI input to NV12(YCbCr420) or NV16(YCbCr422), or use [FFMpeg](./rtsp
```suggestion
When using HDMI RX, gst-mppenc does not support NV24(YCbCr444) and RBG inputs currently, you need to switch the colour format of HDMI input to NV12(YCbCr420) or NV16(YCbCr422), or use [FFmpeg](./rtsp-ffmpeg) for streaming.
```

2023-08-28 02:32 UTC, RadxaYuntian approved these changes

2023-08-28 02:45 UTC, merged