update ROCK 3C 3D file download link
radxa-docs/documentation pull request #194
Opened 2023-08-23 11:00 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-08-23 11:01 UTC, Maycides commented on docs/rock3/rock3c/hardware/revisions.md
> +[v1.34 3D图](https://dl.radxa.com/rock3/docs/hw/3c/rock3c-v1.34.stp)，下载ROCK 3C的 3D文件
```suggestion
[v1.34 3D 图](https://dl.radxa.com/rock3/docs/hw/3c/rock3c-v1.34.stp)，下载 ROCK 3C 的 3D 文件
```

2023-08-23 12:33 UTC, RadxaYuntian requested changes

2023-08-23 12:33 UTC, RadxaYuntian commented on docs/rock3/rock3c/hardware/revisions.md
这个文件名代表的是硬件版本历史的意思，跟正文不符

2023-08-24 03:35 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware/revisions.md
> +[v1.34 3D stp pdf](https://dl.radxa.com/rock3/docs/hw/3c/rock3c-v1.34.stp)��Download 3D stp file of ROCK 3 Model C
```suggestion
[v1.34 3D stp pdf](https://dl.radxa.com/rock3/docs/hw/3c/rock3c-v1.34.stp)
```

2023-08-24 03:35 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware/revisions.md
>  [v1.332 schematic pdf](https://dl.radxa.com/rock3/docs/hw/3c/ROCK-3C-V1.332-SCH.pdf), Download Schematic of ROCK 3 Model C
```suggestion
[v1.332 schematic pdf](https://dl.radxa.com/rock3/docs/hw/3c/ROCK-3C-V1.332-SCH.pdf)
```

2023-08-24 03:35 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware/revisions.md
>  [v1.332 CAM pdf](https://dl.radxa.com/rock3/docs/hw/3c/ROCK-3C-V1.332-SMD.pdf), Download components Position Reference of ROCK 3 Model C
```suggestion
[v1.332 CAM pdf](https://dl.radxa.com/rock3/docs/hw/3c/ROCK-3C-V1.332-SMD.pdf)
```

2023-08-24 03:35 UTC, Maycides commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware/revisions.md
>  [v1.2 2D Top&Bottom dxf](https://dl.radxa.com/rock3/docs/hw/3c/rock3c_v1.2_2d_dxf.zip), Download 2D CAD of ROCK 3 Model C
```suggestion
[v1.2 2D Top&Bottom dxf](https://dl.radxa.com/rock3/docs/hw/3c/rock3c_v1.2_2d_dxf.zip)
```

2023-08-24 04:04 UTC, RadxaYuntian requested changes

2023-08-24 04:04 UTC, RadxaYuntian commented on docs/rock3/rock3c/hardware/download.md
> +# ROCK 3C硬件资料
```suggestion
# 硬件资料
```
分类就是ROCK 3C

2023-08-24 04:04 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware/download.md
> +# ROCK 3C Hardware Information Download
```suggestion
# Hardware Documentation
```

2023-08-24 04:04 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware/download.md
> +sidebar_label: 'Hardware Information'
```suggestion
sidebar_label: 'Hardware Documentation'
```

2023-08-24 04:04 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware/download.md
> +[v1.2 2D Top&Bottom dxf](https://dl.radxa.com/rock3/docs/hw/3c/rock3c_v1.2_2d_dxf.zip)
```suggestion
- [v1.332 Schematic](https://dl.radxa.com/rock3/docs/hw/3c/ROCK-3C-V1.332-SCH.pdf)
- [v1.332 SMD placement map](https://dl.radxa.com/rock3/docs/hw/3c/ROCK-3C-V1.332-SMD.pdf)
- [v1.34 3D STEP](https://dl.radxa.com/rock3/docs/hw/3c/rock3c-v1.34.stp)
- [v1.2 2D DXF](https://dl.radxa.com/rock3/docs/hw/3c/rock3c_v1.2_2d_dxf.zip)
```

2023-08-24 06:38 UTC, RadxaYuntian approved these changes

2023-08-24 06:47 UTC, merged