add zero3w overview
radxa-docs/documentation pull request #196
Opened 2023-08-24 08:17 UTC by wallace77777

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-08-24 08:48 UTC, RadxaYuntian requested changes

2023-08-24 08:48 UTC, RadxaYuntian commented on docs/zero/_category_.json
> +        "description": "ZERO 系列是基于 RK3566、Amlogic A311D、Amlogic A311D SoC的高性能SBC。"
```suggestion
        "description": "ZERO 系列是针对尺寸优化的通用SBC。"
```

2023-08-24 08:48 UTC, RadxaYuntian commented on docs/zero/zero3w/getting-started/overview.md
> +Radxa Zero 3W 是一款高性能单板计算机 (SBC)，外形紧凑，旨在提供无与伦比的计算能力，同时保持卓越的机械兼容性。 Radxa Zero 3W 专为包括制造商、物联网开发人员、业余爱好者和 PC DIY 爱好者在内的多元化用户群量身定制，是一个强大且多功能的平台。 它针对各种应用程序的开发、原型设计和部署进行了优化，从而为将创新理念转化为功能现实提供了可靠的基础。
```suggestion
Radxa ZERO 3W 是一款小尺寸单板计算机，外形紧凑，便于嵌入其他外设共同使用。   
Radxa ZERO 3W 专为包括制造商、物联网开发人员、业余爱好者和 PC DIY 爱好者在内的多元化用户群量身定制，是一个多功能的平台。  
它针对各种应用程序的开发、原型设计和部署进行了优化，从而为将创新理念转化为功能现实提供了可靠的基础。
```
话别说太满，你3566都无与伦比了那3588该怎么说

2023-08-24 08:48 UTC, RadxaYuntian commented on docs/zero/zero3w/getting-started/overview.md
> +|   USB    | 一个微型 USB2 OTG 端口用于供电和数据传输<br/>一个微型 USB2 HOST 端口                      |
```suggestion
|   USB    | 一个 USB 2.0 Type-C OTG 端口用于供电和数据传输<br/>一个 USB 3.0 Type-C HOST 端口                      |
```

2023-08-24 08:48 UTC, RadxaYuntian commented on docs/zero/zero3w/getting-started/overview.md
> +|   SoC    | Rockchip RK3566 SoC Arm Mali™‑G52‑2EE                                                     |
```suggestion
|   SoC    | Rockchip RK3566                                                     |
```
GPU不是SoC的型号

2023-08-24 08:48 UTC, RadxaYuntian commented on docs/zero/zero3w/getting-started/overview.md
> +|   CPU    | 四核 Cortex-A55, 频率高达 1.6Ghz                                                          |
```suggestion
|   CPU    | 四核 Cortex-A55, 频率最高达 1.6Ghz                                                          |
```
频率是动态的

2023-08-24 08:48 UTC, RadxaYuntian commented on docs/zero/zero3w/getting-started/overview.md
> +|   内存   | 1/2 GB LPDDR4                                                                             |
这个可能要确认一下，我记得最大能到8g

2023-08-24 08:48 UTC, RadxaYuntian commented on docs/zero/zero3w/getting-started/overview.md
> +|   显示   | 提供 Micro HDMI接口：支持 1080P@60fps 显示                                                |
```suggestion
|   显示   | 提供 Micro HDMI接口：支持 1080@60p 输出                                                |
```

2023-08-24 08:48 UTC, RadxaYuntian commented on docs/zero/zero3w/getting-started/overview.md
> +| 无线通讯 | 802.11 b/g/n (WiFi 4) Wireless LAN<br/>BT 5.0 with BLE  <br/>可由软件配置板载或外置天线   |
```suggestion
| 无线通讯 | Wi-Fi 4 (802.11 b/g/n)<br/>BT 5.0 with BLE<br/>可由软件配置板载或外置天线   |
```
Wi-Fi 4才是正式名称

2023-08-24 08:48 UTC, RadxaYuntian commented on docs/zero/zero3w/getting-started/overview.md
> +|  摄像头  | 配备 1x4 通道 MIPI CSI（移动行业处理器接口）                                              |
```suggestion
|  摄像头  | 配备 1x4 通道 MIPI CSI                                              |
```

2023-08-24 08:48 UTC, RadxaYuntian commented on docs/zero/zero3w/getting-started/overview.md
> +|   其他   | 40个GPIO扩展座                                                                            |
```suggestion
|   其他   | 一个40针扩展座                                                                            |
```

2023-08-24 08:48 UTC, RadxaYuntian commented on docs/zero/zero3w/getting-started/overview.md
> +|   电源   | USB 2.0 OTG Type-C 电源端口上具有 5V/1A 电源适配器<br/>                                   |
```suggestion
|   电源   | 需要 5V/2A 电源适配器                                   |
```
5V1A好像太低了吧？确认一下

2023-08-24 09:22 UTC, RadxaYuntian commented
你要是从网页提交从这里批量提交：https://github.com/radxa-docs/documentation/pull/196/files

2023-08-24 09:26 UTC, wallace77777 commented on docs/zero/zero3w/getting-started/overview.md
> +|   内存   | 1/2 GB LPDDR4                                                                             |
这个我确认

2023-08-24 09:58 UTC, RadxaYuntian requested changes
英文也要像中文一样修改对应部分

2023-08-24 11:53 UTC, RadxaYuntian approved these changes

2023-08-24 12:00 UTC, merged

2023-08-25 06:45 UTC, Maycides commented
This PR fixed issue #196

2023-08-25 06:47 UTC, RadxaYuntian commented
你这个要在PR正文里面写才行:https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword