Synchronizing the Radxa homepage navigation bar
radxa-docs/documentation pull request #200
Opened 2023-08-25 07:47 UTC by xzuoqi

同步Radxa网站导航栏

2023-08-25 07:48 UTC, xzuoqi reviewed
完成

2023-08-28 02:26 UTC, RadxaYuntian requested changes

2023-08-28 02:26 UTC, RadxaYuntian commented on docusaurus.config.js
> +              },
```suggestion
```
Wiki已经处于维护模式了，不再更新。

2023-08-28 02:26 UTC, RadxaYuntian approved these changes

2023-08-28 02:40 UTC, merged