add zero2 overview
radxa-docs/documentation pull request #203
Opened 2023-08-28 10:07 UTC by wallace77777

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-08-28 10:36 UTC, RadxaYuntian requested changes

2023-08-28 10:36 UTC, RadxaYuntian commented on docs/zero/_category_.json
> +}
文件结尾是要有且只有一个空行的。但是之前不是跟你说了不要操心这个，我回头会一次性修改的

2023-08-28 10:36 UTC, RadxaYuntian commented on docs/zero/zero2/getting-started/overview.md
> +Radxa ZERO2 是一款小尺寸单板计算机，专为嵌入其他外设共同使用而设计。搭载了强大的 Amlogic A311D 处理器作为开发平台，为用户提供卓越的计算性能。多核心架构和高频率运行使其在处理多种复杂任务方面表现出色，涵盖了多媒体处理、图像处理、人工智能和数据分析等领域。此外，该产品还集成了高效的图像和多媒体处理单元，从而支持高清视频的解码和编码，以及流畅的图像渲染。
ZERO和2之间有空格
```suggestion
Radxa ZERO 2 是一款小尺寸单板计算机，专为嵌入其他外设共同使用而设计。搭载了强大的 Amlogic A311D 处理器作为开发平台，为用户提供卓越的计算性能。多核心架构和高频率运行使其在处理多种复杂任务方面表现出色，涵盖了多媒体处理、图像处理、人工智能和数据分析等领域。此外，该产品还集成了高效的图像和多媒体处理单元，从而支持高清视频的解码和编码，以及流畅的图像渲染。
```

2023-08-28 10:36 UTC, RadxaYuntian commented on docs/zero/zero2/getting-started/overview.md
> +为了最大程度释放 Radxa ZERO2 的性能，专门配备了定制的散热模组。散热模组采用铝质材质，并设计有多鳍片结构，从而有效增大了散热表面积。此外，还采用了可编程控制的散热风扇，该风扇能够根据设备当前的负载和温度需求动态调整转速，以避免不必要的能源消耗，提高能效，从而降低电力消耗和热量产生。这使得Radxa ZERO2在高负载情况下能够保持稳定的性能表现，提供卓越的使用体验。
```suggestion
为了最大程度释放 Radxa ZERO 2 的性能，专门配备了定制的散热模组。散热模组采用铝质材质，并设计有多鳍片结构，从而有效增大了散热表面积。此外，还采用了可编程控制的散热风扇，该风扇能够根据设备当前的负载和温度需求动态调整转速，以避免不必要的能源消耗，提高能效，从而降低电力消耗和热量产生。这使得Radxa ZERO 2在高负载情况下能够保持稳定的性能表现，提供卓越的使用体验。
```

2023-08-28 10:36 UTC, RadxaYuntian commented on docs/zero/zero2/getting-started/overview.md
> +| 包裹清单 |           1x Radxa Zero 2 <br/>1x 散热模块<br/>1x 导热硅胶<br/>1x 天线           |
```suggestion
| 包裹清单 |           1x Radxa ZERO 2 <br/>1x 散热模块<br/>1x 导热硅胶<br/>1x 天线           |
```

2023-08-28 10:36 UTC, RadxaYuntian commented on docs/zero/zero2/getting-started/overview.md
> +|   显示   |       一个 Micro HDMI 接口：支持  4Kp60 输出<br/>一个 4 通道 MIPI DSI 接口       |
```suggestion
|   显示   |       一个 Micro HDMI 接口：支持 4Kp60 输出<br/>一个 4 通道 MIPI DSI 接口       |
```

2023-08-28 10:54 UTC, wallace77777 commented on src/css/custom.css
> +}
这些都是拿现成的图片，自己调整要好几次费时间才能查看展示效果图，不如直接css调整更灵活

2023-08-28 10:54 UTC, wallace77777 commented on docs/zero/_category_.json
> +}
这个应该是不小心点到了

2023-08-28 10:59 UTC, RadxaYuntian commented on docs/zero/_category_.json
> +}
你自己在files changed里面看看就知道了，已有文件的结尾空行都被你删掉了。这个我之后会处理的

2023-08-28 11:03 UTC, RadxaYuntian commented on src/css/custom.css
> +}
那这种仅仅局限于一个文件用的css应该可以用`<div className='img' style='transform: scale(.6)'>`吧？这样不用污染公共的custom.css

2023-08-28 11:13 UTC, wallace77777 commented on src/css/custom.css
> +}
不会污染公共的custom.css

2023-08-28 11:22 UTC, RadxaYuntian commented on src/css/custom.css
> +}
你这个commit已经把自用的css写到公共的costom.css里面了啊

2023-08-29 08:39 UTC, wallace77777 commented on src/css/custom.css
> +}
<div className='img' style='transform: scale(.6)'>这个方法不行，会报错

2023-08-29 08:44 UTC, wallace77777 commented on src/css/custom.css
> +}
<div className='img' style='transform: scale(.6)'>这个方法会报错，试了下其他方法也还不行，还有其他方法吗

2023-08-29 08:45 UTC, wallace77777 commented on src/css/custom.css
> +}
用“<div className='img' style='transform: scale(.6)'>”这个会报错，试了下其他还是不行，还有其他方法吗

2023-08-29 08:47 UTC, wallace77777 commented on src/css/custom.css
> +}
`<div className='img' style='transform: scale(.6)'>`这个会报错，试了下其他方法还是不行，有其他方法吗

2023-08-30 03:05 UTC, RadxaYuntian commented on src/css/custom.css
> +}
错误不是都说的很明确了么？`The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.`

要换个语法表达：
`<div className='img' style={{ transform: 'scale(.6)' }}>`

2023-08-30 08:02 UTC, RadxaYuntian approved these changes

2023-08-30 08:08 UTC, merged