add libmraa tutorial
radxa-docs/documentation pull request #226
Opened 2023-09-11 11:59 UTC by nascs

2023-09-12 02:17 UTC, RadxaYuntian commented
CI有错误，可以看一看最后的报错消息，会告诉你怎么自动修复
另外分支也没有pull到最新

2023-09-13 06:20 UTC, RadxaYuntian requested changes

2023-09-13 06:20 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +- show： 显示所选 uart 的设置
要列出完整的mraa-uart命令，如果有些是开关的话就不用列出

2023-09-13 06:42 UTC, nascs commented on docs/general-tutorial/mraa.md
> +- show： 显示所选 uart 的设置
完整命令是这样的 mraa-uart { list | dev device } [ baud bps ] [ databits d ] [ parity p ] [ stopbits s ] [ ctsrts mode ] [ send string ] [ recv timeout ] [ show ]

[] 里面的都是可选参数

2023-09-13 07:30 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +- show： 显示所选 uart 的设置
你跟上面的格式没有差别，读者怎么知道这些是参数而不是命令？这样就不要把具体参数列出来

2023-10-10 08:25 UTC, RadxaYuntian requested changes
1. 同步修改到英文版本
2. 你的分支pull一下，和上游head对齐，不然没法合并

2023-10-10 08:25 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +Eclipse Mraa（Libmraa）是一个与 Java、Python 和 JavaScript 绑定的 C/C++ 库，用于连接各种物联网和边缘平台上的 I/O 引脚和总线，其 API 结构合理，端口名称/编号与所在的电路板相匹配。
```suggestion
Eclipse Mraa（Libmraa）是一个包含 Java、Python 和 JavaScript 绑定的 C/C++ 库，用于连接各种物联网和边缘平台上的 I/O 引脚和总线，其 API 结构合理，端口名称/编号与所在的电路板相匹配。
```

2023-10-10 08:25 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +# 在 Radxa 板子上安装 MRAA
```suggestion
## 安装 MRAA
```
我们只给我们自己写文档

2023-10-10 08:25 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +## gpio
```suggestion
### GPIO
```

2023-10-10 08:25 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +## i2c
```suggestion
### I2C
```

2023-10-10 08:25 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +## uart
```suggestion
### UART
```

2023-10-10 08:25 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +- mraa-uart list： 列出所有可用 uart 端口
```suggestion
- mraa-uart list： 列出所有可用 UART 端口
```

2023-10-10 08:25 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +- [github](https://github.com/eclipse/mraa)
```suggestion
- [GitHub](https://github.com/eclipse/mraa)
```

2023-10-10 08:25 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +# MRAA 命令行工具
```suggestion
## MRAA 命令行工具
```

2023-10-10 08:25 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +# 参考
```suggestion
## 参考
```

2023-10-10 08:25 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +- [mraa 官网](https://iotdk.intel.com/docs/master/mraa/index.html)
```suggestion
- [Mraa API 文档](https://iotdk.intel.com/docs/master/mraa/index.html)
```

2023-10-10 11:31 UTC, RadxaYuntian requested changes
英文没有同步更新

2023-10-10 11:51 UTC, RadxaYuntian requested changes
直接把中文文档丢机器翻译不好么？

2023-10-10 11:51 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/mraa.md
> +- mraa-uart list: Lists uarts on the system (non intrusive)
```suggestion
- mraa-uart list: Lists UARTs on the system
```

2023-10-10 11:51 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/mraa.md
> +- mraa-i2c list: List available busses
```suggestion
- mraa-i2c list: List available I2C buses
```

2023-10-10 11:51 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/mraa.md
> +## Install MRAA on Radxa boards
```suggestion
## Install MRAA
```

2023-10-10 11:51 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/mraa.md
> +- [github](https://github.com/eclipse/mraa)
```suggestion
- [GitHub](https://github.com/eclipse/mraa)
```

2023-10-10 11:51 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/mraa.md
> +# More
```suggestion
## More
```

2023-10-10 11:51 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/mraa.md
> +- [mraa official website](https://iotdk.intel.com/docs/master/mraa/index.html)
```suggestion
- [Mraa API reference](https://iotdk.intel.com/docs/master/mraa/index.html)
```

2023-10-10 11:51 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +- mraa-i2c list： 列出所有可用 i2c 总线
```suggestion
- mraa-i2c list： 列出所有可用 I2C 总线
```

2023-10-10 11:51 UTC, RadxaYuntian approved these changes

2023-10-10 11:52 UTC, RadxaYuntian commented on docs/general-tutorial/mraa.md
> +- show： 显示所选 uart 的设置
懒得管了

2023-10-10 12:04 UTC, merged