添加安装 Panfrost 开源驱动
radxa-docs/documentation pull request #233
Opened 2023-09-20 07:45 UTC by CodeChenL

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-09-20 07:45 UTC, CodeChenL commented
粗稿

2023-09-20 09:18 UTC, CodeChenL commented
#231

2023-09-20 09:23 UTC, RadxaYuntian requested changes

2023-09-20 09:23 UTC, RadxaYuntian commented on docs/general-tutorial/panfrost.md
> +sidebar_label: "安装 Panfrost 开源驱动"
```suggestion
sidebar_label: "RK3588 安装 Panfork 开源驱动"
```
后文都需要改成panfork。这个驱动和上游panfrost不是一回事

2023-09-20 09:23 UTC, RadxaYuntian commented on docs/general-tutorial/panfrost.md
> +sudo apt install xserver-xorg-core="$(apt-cache show xserver-xorg-core | grep Version | grep -v "$(dpkg -s xserver-xorg-core | grep Version)" | cut -d" " -f2)" xserver-common="$(apt-cache show xserve
这个命令有点hack了。我感觉可以用[`-t`参数](https://superuser.com/a/726809)来指定仓库

2023-09-20 09:23 UTC, RadxaYuntian commented on docs/general-tutorial/panfrost.md
> +驱动运行在Wayland下性能更嘉，可使用 apt 安装 kde Wayland 会话：plasma-workspace-wayland，并在SDDM登录界面选择对应会话。
```suggestion
驱动运行在 Wayland 下性能更佳，可使用 apt 安装 `plasma-workspace-wayland`，并在 SDDM 登录界面选择对应会话。
```
关注嘉然顿顿解馋

2023-09-20 09:23 UTC, RadxaYuntian commented on docs/general-tutorial/panfrost.md
> +sudo apt install glmark-x11 #如果桌面运行在 Wayland 环境下可安装 glmark-wayland
少了个执行应用的命令

2023-09-20 09:43 UTC, CodeChenL commented on docs/general-tutorial/panfrost.md
> +sudo apt install xserver-xorg-core="$(apt-cache show xserver-xorg-core | grep Version | grep -v "$(dpkg -s xserver-xorg-core | grep Version)" | cut -d" " -f2)" xserver-common="$(apt-cache show xserve
貌似不行 `-t bullseye`和`-t rockchip-bullseye`都是从radxa-repo下
```bash
rock@rock-5b:~$ sudo apt --reinstall install -t bullseye xserver-xorg-core xserver-common 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  kwin-wayland-backend-drm
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 2 reinstalled, 0 to remove and 3 not upgraded.
Need to get 1,373 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://radxa-repo.github.io/bullseye rockchip-bullseye/main arm64 xserver-common all 2:1.20.11-1+deb11u3 [73.5 kB]
Get:2 https://radxa-repo.github.io/bullseye rockchip-bullseye/main arm64 xserver-xorg-core arm64 2:1.20.11-1+deb11u3 [1,299 kB]
Fetched 1,373 kB in 2s (776 kB/s)              
(Reading database ... 155050 files and directories currently installed.)
Preparing to unpack .../xserver-common_2%3a1.20.11-1+deb11u3_all.deb ...
Unpacking xserver-common (2:1.20.11-1+deb11u3) over (2:1.20.11-1+deb11u3) ...
Preparing to unpack .../xserver-xorg-core_2%3a1.20.11-1+deb11u3_arm64.deb ...
Unpacking xserver-xorg-core (2:1.20.11-1+deb11u3) over (2:1.20.11-1+deb11u3) ...
Setting up xserver-common (2:1.20.11-1+deb11u3) ...
Setting up xserver-xorg-core (2:1.20.11-1+deb11u3) ...
Processing triggers for man-db (2.9.4-2) ...
rock@rock-5b:~$ 
```

2023-09-20 09:47 UTC, RadxaYuntian commented on docs/general-tutorial/panfrost.md
> +sudo apt install xserver-xorg-core="$(apt-cache show xserver-xorg-core | grep Version | grep -v "$(dpkg -s xserver-xorg-core | grep Version)" | cut -d" " -f2)" xserver-common="$(apt-cache show xserve
```
       install, reinstall, remove, purge (apt-get(8))
           ...
           Alternatively the version from a specific
           release can be selected by following the package name with a
           forward slash (/) and codename (bullseye, bookworm, sid ...) or
           suite name (stable, testing, unstable).
```

2023-09-20 09:59 UTC, CodeChenL commented on docs/general-tutorial/panfrost.md
> +sudo apt install glmark-x11 #如果桌面运行在 Wayland 环境下可安装 glmark-wayland
已修复

2023-09-20 10:13 UTC, RadxaYuntian commented on docs/general-tutorial/panfrost.md
> +sudo apt install xserver-xorg-core="$(apt-cache show xserver-xorg-core | grep Version | grep -v "$(dpkg -s xserver-xorg-core | grep Version)" | cut -d" " -f2)" xserver-common="$(apt-cache show xserve
这个其实是man apt,不仅仅局限于apt-get。不过不是什么大问题

2023-09-20 10:14 UTC, RadxaYuntian approved these changes
麻烦squash一下后补充英文文档

2023-09-20 10:21 UTC, CodeChenL commented
好的

2023-09-20 20:29 UTC, CodeChenL commented
已翻译

2023-09-21 03:56 UTC, RadxaYuntian approved these changes

2023-09-21 03:57 UTC, RadxaYuntian commented on docs/general-tutorial/panfork.md
> +#   如需恢复 Rockchip Xorg server，请运行一下命令
```suggestion
#   如需恢复 Rockchip Xorg server，请运行以下命令
```

2023-09-21 03:57 UTC, RadxaYuntian approved these changes

2023-09-21 07:26 UTC, CodeChenL commented
怎么看不到自动合并检查情况

2023-09-21 07:29 UTC, RadxaYuntian commented
不知道为什么没有触发，你suqash一下然后force push上来触发吧

2023-09-21 07:35 UTC, CodeChenL commented
那我知道怎么回事了，我把我的仓库的action关闭了，因为老是报错

2023-09-21 07:36 UTC, CodeChenL commented
我重新开了action，你再开启自动合并试试？

2023-09-21 07:38 UTC, RadxaYuntian commented
应该你要自己在action里面手动触发一下，我这边自动合并是不会再次触发CI的

2023-09-21 07:39 UTC, RadxaYuntian commented
我看你那边报错是没有开github pages，我回头改一下CI

2023-09-21 08:07 UTC, merged