Add Zero2 start guide
radxa-docs/documentation pull request #242
Opened 2023-09-27 03:54 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-09-27 03:56 UTC, Maycides commented
目前缺 loader 文件

2023-10-10 08:26 UTC, RadxaYuntian commented
ZERO 2改名成ZERO 2 PRO了

2023-10-10 09:50 UTC, Maycides commented
在更新成pro

2023-10-10 10:35 UTC, Maycides commented
镜像等release了放在zero文件夹下吧  还是就是loader那儿

2023-10-10 10:36 UTC, RadxaYuntian commented
有个zero2的文件夹，你没看么？

2023-10-10 10:45 UTC, RadxaYuntian requested changes

2023-10-10 10:45 UTC, RadxaYuntian commented on docs/zero/official-images.md
> +# Radxa Zero 系列官方镜像
```suggestion
# Radxa ZERO 系列官方镜像
```
ZERO和ROCK一样要全大写

2023-10-10 10:45 UTC, RadxaYuntian commented on docs/zero/zero2pro/_category_.json
> +  "label": "ZERO 2 Pro",
```suggestion
  "label": "ZERO 2 PRO",
```

2023-10-10 10:45 UTC, RadxaYuntian commented on docs/zero/zero2pro/_category_.json
>      "description": "ZERO 2 是一款基于 Amlogic A311D SOC 的高性能单板计算机。",
```suggestion
    "description": "ZERO 2 PRO 是一款基于 Amlogic A311D SOC 的高性能单板计算机。",
```

2023-10-10 10:45 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +本指南是为 瑞莎 Zero 2 Pro 初级使用者编写，可以帮助您了解 瑞莎 Zero 2 Pro 基本的准备和设置。
ZERO 2 PRO

2023-10-10 10:45 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +我们将尽可能多地介绍相关信息。
```suggestion
```
这个没必要说吧

2023-10-10 10:45 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +- 瑞莎 Zero 2 Pro SBC
```suggestion
- 瑞莎 ZERO 2 PRO
```
产品名是个专有名字，不用加SBC定义

2023-10-10 10:45 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +- microSD 卡，容量不小于 8GB（如果您的 Zero 2 Pro 配备板载 eMMC，您可以直接将系统烧录其中）
好像ZERO 2标配eMMC？确认一下

2023-10-10 10:45 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +  Zero 2 Pro 拥有两个 Type-C 接口，其中一个用于供电时，另一个可使用 Type-C 分线器来扩展键鼠或其他外设。
```suggestion
- Type-C 集线器及 USB 键鼠  
  Zero 2 Pro 拥有两个 Type-C 接口，其中一个用于供电时，另一个可使用 Type-C 集线器来扩展键鼠或其他外设。
```

2023-10-10 10:45 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +  Zero 2 Pro 配备的是 micro HDMI 接口。建议使用具有 HDMI 功能的显示器，最高支持 1920 x 1080 的分辨率。
```suggestion
  Zero 2 Pro 配备的是 micro HDMI 接口。建议使用具有 HDMI 功能的显示器，最高支持 4K60p 分辨率。
```

2023-10-10 10:45 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +  sudo boot-g12.py .bin
```suggestion
sudo boot-g12.py .bin
```

2023-10-11 02:31 UTC, RadxaYuntian commented
loader已上传：https://dl.radxa.com/zero2/images/loader/

2023-10-11 02:56 UTC, Maycides commented on docs/zero/zero2pro/getting-started/getting-start.md
> +- microSD 卡，容量不小于 8GB（如果您的 Zero 2 Pro 配备板载 eMMC，您可以直接将系统烧录其中）
有不带的选项

2023-10-11 03:11 UTC, RadxaYuntian requested changes

2023-10-11 03:11 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/zero/official-images.md
> +# Radxa Zero Series Official Images
```suggestion
# Radxa ZERO Series Official Images
```

2023-10-11 03:12 UTC, RadxaYuntian approved these changes

2023-10-11 03:13 UTC, RadxaYuntian requested changes

2023-10-11 03:13 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +
要加上loader的链接

2023-10-11 03:18 UTC, Maycides commented on docs/zero/zero2pro/getting-started/getting-start.md
> +
刚加上了

2023-10-11 03:19 UTC, RadxaYuntian requested changes
这个可以做一个markdown列表

2023-10-11 03:19 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +[u-boot.bin.sd.bin](https://dl.radxa.com/zero2/images/loader/u-boot.bin.sd.bin)：用于 eMMC/microSD 启动的主线 U-Boot 引导加载程序。请参阅本指南，了解如何在已安装操作系统的情况下闪存它。
```suggestion
[u-boot.bin.sd.bin](https://dl.radxa.com/zero2/images/loader/u-boot.bin.sd.bin)：用于 eMMC/microSD 启动的主线 U-Boot 引导加载程序。
```
本指南不涉及此内容

2023-10-11 03:19 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero2pro/getting-started/getting-start.md
> +[u-boot.bin.sd.bin](https://dl.radxa.com/zero2/images/loader/u-boot.bin.sd.bin): mainline U-Boot bootloader for eMMC/microSD boot. Please refer to this guide to see how to flash it when OS is already
```suggestion
[u-boot.bin.sd.bin](https://dl.radxa.com/zero2/images/loader/u-boot.bin.sd.bin): mainline U-Boot bootloader for eMMC/microSD boot.
```

2023-10-11 03:46 UTC, RadxaYuntian approved these changes

2023-10-11 03:49 UTC, RadxaYuntian requested changes

2023-10-11 03:49 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +  boot-g12.py loader.bin
```suggestion
boot-g12.py radxa-zero2-2pro-erase-emmc.bin
```

2023-10-11 03:49 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +sudo boot-g12.py .bin
```suggestion
sudo boot-g12.py radxa-zero2-2pro-erase-emmc.bin
```

2023-10-11 03:49 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +工具检测到 Maskrom 模式后，你就可以点击 `Select` 按钮来选择镜像文件，然后点击 `Run` 按钮进行烧录：
```suggestion
工具检测到 Maskrom 模式后，你就可以点击 `Select` 按钮来选择 Loader 文件，然后点击 `Run` 按钮进行加载：
```

2023-10-11 07:40 UTC, RadxaYuntian approved these changes

2023-10-11 07:40 UTC, RadxaYuntian commented on docs/zero/zero2pro/getting-started/getting-start.md
> +其中，`loader.bin` 更换为您需要烧录的固件，您可以在下文中获得下载链接。
```suggestion
在此之后，您的电脑将会将瑞莎 ZERO 2 PRO 识别为一个 USB 存储设备，您只需按照[操作系统安装指南](/general-tutorial/os-installation)中的操作将系统镜像烧录其中，再正常启动即可。
```

2023-10-11 07:40 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero2pro/getting-started/getting-start.md
> +Where `loader.bin` is replaced with the firmware you need to flash, you can get the download link below.
```suggestion
After that, your computer will recognise the Radxa ZERO 2 PRO as a USB storage device, and you just need to follow the instructions in the [OS Installation Guide](/general-tutorial/os-installation) to flash the system image into it, and then boot it up normally.
```

2023-10-11 07:41 UTC, RadxaYuntian approved these changes

2023-10-11 07:55 UTC, merged