Update the spi flash configuration description of rock4 se
radxa-docs/documentation pull request #246
Opened 2023-10-10 06:11 UTC by vamrs-feng

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-10-10 08:18 UTC, RadxaYuntian commented
建议类似wiki单独给spi设置一个页面：https://wiki.radxa.com/Rockpi4/hardware/spi_flash

2023-10-10 10:05 UTC, vamrs-feng commented
> 建议类似wiki单独给spi设置一个页面：https://wiki.radxa.com/Rockpi4/hardware/spi_flash

暂时先放这吧。

2023-10-10 10:16 UTC, RadxaYuntian commented
就现在这个内容我感觉没有必要合并。第一spi是个焊接件，不适合放在getting-started里面。第二spi的overlay源代码也不应该直接在getting started里面给出去。我们现在让用户用rsetup就是要让他们不去看代码

2023-10-21 06:28 UTC, peterwang2050 approved these changes

2023-10-21 06:29 UTC, peterwang2050 approved these changes

2023-10-23 02:11 UTC, RadxaYuntian requested changes
当前的内容不适合放在这个位置

2023-11-13 03:33 UTC, closed without merging