add zero3w antenna docs
radxa-docs/documentation pull request #247
Opened 2023-10-10 09:44 UTC by Radxa-Alvin

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-10-10 09:49 UTC, RadxaYuntian requested changes
先处理CI的错误吧

2023-10-10 09:49 UTC, RadxaYuntian commented on docs/zero/zero3w/hardware/zero3w-antenna.md
> +sidebar_label: "天线"
```suggestion
sidebar_label: "射频天线"
```

2023-10-10 09:49 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero3w/hardware/zero3w-antenna.md
> +sidebar_label: "ANTENNA"
```suggestion
sidebar_label: "Antenna"
```

2023-10-10 09:49 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero3w/hardware/zero3w-antenna.md
> +# RF ANTENNA
```suggestion
# RF Antenna
```

2023-10-10 10:07 UTC, RadxaYuntian submitted a review, later dismissed

2023-10-10 10:07 UTC, RadxaYuntian commented on docs/zero/zero3w/hardware/zero3w-antenna.md
> +![zero3w antenna2 ](/img/zero/zero3w/zero3w-antenna2.webp)
```suggestion
如下图所示，ZERO 3W 同时拥有一个板载天线和一个外置天线接口：

![zero3w antenna](/img/zero/zero3w/zero3w-antenna1.webp)

两个天线不能同时工作，并且在默认情况下优先使用板载天线。

如果需要使用外置天线, 请参考[启用设备树](/radxa-os/rsetup/devicetree)一章，使用`rsetup`来开启对应的 overlay。
```

2023-10-10 10:07 UTC, RadxaYuntian commented on static/img/zero/zero3w/zero3w-antenna2.webp
不再使用，可以删除

2023-10-10 10:07 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero3w/hardware/zero3w-antenna.md
需要和中文内容同步

2023-10-10 10:13 UTC, Radxa-Alvin commented on docs/zero/zero3w/hardware/zero3w-antenna.md
> +![zero3w antenna2 ](/img/zero/zero3w/zero3w-antenna2.webp)
当前页面可以呈现的东西就没必要再跳转一次到别的链接了吧?

2023-10-10 10:19 UTC, RadxaYuntian commented on docs/zero/zero3w/hardware/zero3w-antenna.md
> +![zero3w antenna2 ](/img/zero/zero3w/zero3w-antenna2.webp)
用户不一定知道rsetup怎么用。你就放一个`sudo rsetup`就能显示你`zero3w-antenna2.webp`里面的列表么？

2023-10-10 10:22 UTC, Radxa-Alvin commented on docs/zero/zero3w/hardware/zero3w-antenna.md
> +![zero3w antenna2 ](/img/zero/zero3w/zero3w-antenna2.webp)
当前呈现的天线的overlay选择, 需要告知用户选择哪个overlay ,至于overlay的使用属于基础教程,需要在其他地方引导用户先熟悉基础工具的使用

2023-10-11 02:14 UTC, peterwang2050 approved these changes

2023-10-11 02:24 UTC, merged