update zero 3w picturs and add revision info
radxa-docs/documentation pull request #263
Opened 2023-10-13 09:18 UTC by melooooooooooo

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-10-18 06:23 UTC, RadxaYuntian requested changes

2023-10-18 06:23 UTC, RadxaYuntian commented on yarn.lock
内容pr不要带上这个文件，#258有更新这个

2023-10-26 07:06 UTC, RadxaYuntian submitted a review, later dismissed

2023-10-26 07:06 UTC, RadxaYuntian commented on yarn.lock
这个不能删的，只需要你不动这个文件

2023-11-03 06:23 UTC, RadxaYuntian commented
如果改好了就把这个pr reopen,不要重新开一个新的

2023-11-03 11:59 UTC, peterwang2050 approved these changes

2023-11-03 12:13 UTC, merged