add use-uart2-as-application-uart.md
radxa-docs/documentation pull request #264
Opened 2023-10-15 09:02 UTC by CodeChenL

###### Description of changes

#187 
###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-10-15 17:20 UTC, CodeChenL commented
![image](https://github.com/radxa-docs/documentation/assets/43897062/5ad1daec-7dde-453c-afb1-d67d112f4da8)
新的代码检查貌似不兼容Windows？
我已经压到8KB了

2023-10-15 19:28 UTC, CodeChenL commented
#257

2023-10-17 03:03 UTC, RadxaYuntian requested changes

2023-10-17 03:03 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +sudo rsetup
```suggestion
rsetup
```
rsetup会自动根据运行环境使用原生的提权工具（sudo或pkexec）。同时最新的rsetup也提供了XDG Desktop Entry，可以从图形化启动器打开。

2023-10-17 03:03 UTC, RadxaYuntian commented on docs/general-tutorial/use-uart2-as-application-uart.md
> +
```suggestion
sudo nano /etc/kernel/cmdline
# 删除所有 ttyFIQ0 和 ttyS2 相关的 console 参数，如 "console=ttyFIQ0,1500000n8"
sudo u-boot-update
```
可以保留tty1的图形终端

2023-10-17 03:03 UTC, RadxaYuntian commented on docs/general-tutorial/use-uart2-as-application-uart.md
> +### 勾选后选择 OK ，然后退出 rsetup
可能直接引用rsetup的设备树配置说明页面，这里只用简单说一下需要打开Enable UART2-M0即可

2023-10-17 05:14 UTC, CodeChenL commented on docs/general-tutorial/add-led.md
> +sudo rsetup
![image](https://github.com/radxa-docs/documentation/assets/43897062/f3afabdf-2f78-472d-82ec-952231091ea7)
我这实测是不行的

2023-10-17 05:16 UTC, CodeChenL commented on docs/general-tutorial/add-led.md
> +sudo vim /boot/user_led3.dts
你可以看看提交的static/img/general-tutorial/enable-user-led3.webp文件，文件选择界面不会滚动，并且挡住了OK和退出键，这就是我暂时为什么建在boot分区的原因， 那里文件少好选择。
是否需要给rsetup提issues？

2023-10-17 05:59 UTC, CodeChenL commented
今天课比较满，今晚到明天我再补充吧
还有#261 这个我可以写

2023-10-17 06:25 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +sudo vim /boot/user_led3.dts
这个应该是whiptail的局限吧。我看有个`--scrolltext`，但是只限文本框的样子。可以先提一个记录一下

2023-10-17 06:44 UTC, CodeChenL commented on docs/general-tutorial/add-led.md
> +                            linux,default-trigger = "disk-activity";    #设置默认触发器为 disk-activity
![image](https://github.com/radxa-docs/documentation/assets/43897062/f5651f82-726e-4ca2-9f9f-ec1502887c03)
貌似没有这个模块，我测试了default-on可以，就天真的以为可以随便换，原来还需要对应模块啊（

2023-10-17 06:46 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +sudo rsetup
从串口和SSH执行rsetup，都能正确识别到当前没有桌面环境，使用sudo：https://asciinema.org/a/Cg1x7TZPxu6Vq88Dq0suntp7r
我从KDE里面launcher->settings执行rsetup的桌面entry或者从konsole命令行执行，都有KDE的PolicyKit agent提示。
命令行的pkexec agent我也的确是不能用，所以有检测当前是否是图形界面，不是则用sudo，而不是统一都用pkexec:https://github.com/radxa-pkg/rsetup/blob/main/src/usr/bin/rsetup#L20-L25
不知道你这是个什么环境，怎么有图形环境但是少了图形化的policy kit：https://packages.debian.org/bullseye/polkit-kde-agent-1

2023-10-17 06:49 UTC, CodeChenL commented on docs/general-tutorial/add-led.md
> +sudo rsetup
我是在使用ssh，可能和windterm默认开启x11转发有关？

2023-10-17 06:54 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +                            linux,default-trigger = "disk-activity";    #设置默认触发器为 disk-activity
要看具体内核是怎么配置的：
```
radxa@rock-pi-e:~$ grep -i leds_trig /boot/config-6.1.57-1-stable 
# CONFIG_USB_LEDS_TRIGGER_USBPORT is not set
CONFIG_LEDS_TRIGGERS=y
CONFIG_LEDS_TRIGGER_TIMER=m
CONFIG_LEDS_TRIGGER_ONESHOT=m
CONFIG_LEDS_TRIGGER_DISK=y
CONFIG_LEDS_TRIGGER_MTD=y
CONFIG_LEDS_TRIGGER_HEARTBEAT=m
CONFIG_LEDS_TRIGGER_BACKLIGHT=m
CONFIG_LEDS_TRIGGER_CPU=y
CONFIG_LEDS_TRIGGER_ACTIVITY=m
CONFIG_LEDS_TRIGGER_GPIO=m
CONFIG_LEDS_TRIGGER_DEFAULT_ON=m
CONFIG_LEDS_TRIGGER_TRANSIENT=m
CONFIG_LEDS_TRIGGER_CAMERA=m
CONFIG_LEDS_TRIGGER_PANIC=y
CONFIG_LEDS_TRIGGER_NETDEV=m
CONFIG_LEDS_TRIGGER_PATTERN=m
CONFIG_LEDS_TRIGGER_AUDIO=m
# CONFIG_LEDS_TRIGGER_TTY is not set
```
不过disk-activity应该是[只有y/n](https://cateee.net/lkddb/web-lkddb/LEDS_TRIGGER_DISK.html)，没有m的选项。我当时写的时候也没去详细检查这个

2023-10-17 06:55 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +sudo rsetup
那有可能，我得看看这个该怎么检测

2023-10-17 06:59 UTC, CodeChenL commented on docs/general-tutorial/add-led.md
> +sudo rsetup
我把默认x11转发关了就能调用sudo了

2023-10-17 07:00 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +sudo rsetup
我已经为这个建了个issue了

2023-10-17 07:01 UTC, CodeChenL commented on docs/general-tutorial/add-led.md
> +                            linux,default-trigger = "disk-activity";    #设置默认触发器为 disk-activity
那现在是给内核提pr还是修改教程的触发器？
等等瞧瞧我发现了什么，bsp的6.1内核？

2023-10-17 07:03 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +                            linux,default-trigger = "disk-activity";    #设置默认触发器为 disk-activity
内核应该是有默认开启这个的，所以就这个trigger来说，教程是不用改的。你可以自己看看你5B上的config来确认这一点
这个6.1是[上游](https://github.com/radxa-repo/bsp/blob/main/linux/stable/fork.conf#L1-L2)的

2023-10-17 07:22 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +sudo vim /boot/user_led3.dts
另外rsetup本身是支持命令行[直接调用自带函数](https://github.com/radxa-pkg/rsetup/blob/main/src/usr/bin/rsetup#L33)的，可以直接[`rsetup compile_dtb "$item" "$U_BOOT_FDT_OVERLAYS_DIR/$basename"`](https://github.com/radxa-pkg/rsetup/blob/main/src/usr/lib/rsetup/mod/overlay.sh#L3)编译dtb。不过这种使用方式目前是属于undocumented feature，还没决定好到底怎么支持

2023-10-17 07:24 UTC, CodeChenL commented on docs/general-tutorial/add-led.md
> +                            linux,default-trigger = "disk-activity";    #设置默认触发器为 disk-activity
```bash
rock@rock-5b:~$ zcat /proc/config.gz | grep -i LEDS_TRIGGER
# CONFIG_USB_LEDS_TRIGGER_USBPORT is not set
CONFIG_LEDS_TRIGGERS=y
CONFIG_LEDS_TRIGGER_TIMER=m
CONFIG_LEDS_TRIGGER_ONESHOT=m
CONFIG_LEDS_TRIGGER_DISK=y
CONFIG_LEDS_TRIGGER_MTD=y
CONFIG_LEDS_TRIGGER_HEARTBEAT=m
CONFIG_LEDS_TRIGGER_BACKLIGHT=m
CONFIG_LEDS_TRIGGER_CPU=y
CONFIG_LEDS_TRIGGER_ACTIVITY=m
CONFIG_LEDS_TRIGGER_GPIO=m
CONFIG_LEDS_TRIGGER_DEFAULT_ON=m
CONFIG_LEDS_TRIGGER_TRANSIENT=m
CONFIG_LEDS_TRIGGER_CAMERA=m
CONFIG_LEDS_TRIGGER_PANIC=y
CONFIG_LEDS_TRIGGER_NETDEV=m
CONFIG_LEDS_TRIGGER_PATTERN=m
CONFIG_LEDS_TRIGGER_AUDIO=m
rock@rock-5b:~$ 
```
`CONFIG_LEDS_TRIGGER_DISK=y`包含disk-activity吗
只能在课间回复，所以回复有点慢，抱歉

2023-10-17 07:26 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +                            linux,default-trigger = "disk-activity";    #设置默认触发器为 disk-activity
有的：
https://github.com/radxa/kernel/blob/linux-5.10-gen-rkr3.4/drivers/leds/trigger/Makefile#L4
https://github.com/radxa/kernel/blob/linux-5.10-gen-rkr3.4/drivers/leds/trigger/ledtrig-disk.c#L40-L43

2023-10-17 07:32 UTC, CodeChenL commented on docs/general-tutorial/add-led.md
> +                            linux,default-trigger = "disk-activity";    #设置默认触发器为 disk-activity
换成mmc1触发器可以了，那看来教程不用改触发器了

2023-10-17 07:33 UTC, CodeChenL commented on docs/general-tutorial/add-led.md
> +                            linux,default-trigger = "disk-activity";    #设置默认触发器为 disk-activity
不过可以加个提示，如果是使用sd卡换成mmc1触发器

2023-10-17 07:39 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +                            linux,default-trigger = "disk-activity";    #设置默认触发器为 disk-activity
这个trigger和ATA相关的：https://github.com/radxa/kernel/commits/linux-5.10-gen-rkr3.4/drivers/leds/trigger/ledtrig-disk.c

2023-10-17 07:44 UTC, CodeChenL commented on docs/general-tutorial/add-led.md
> +                            linux,default-trigger = "disk-activity";    #设置默认触发器为 disk-activity
那我还是把教程的触发器改成mmc吧

2023-10-17 20:01 UTC, CodeChenL commented
review一下没问题的话可以先合并了
#261 新开一个pr

2023-10-18 02:41 UTC, RadxaYuntian requested changes

2023-10-18 02:41 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +# 按照一下选项进入加载设备树覆写文件（DTBO）界面
```suggestion
# 按照以下选项进入加载设备树覆写文件（DTBO）界面
```

2023-10-18 02:48 UTC, RadxaYuntian requested changes

2023-10-18 02:48 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +            };
```suggestion
            custom-leds{                                          /* 添加 custom-leds 节点 */
                compatible = "gpio-leds";
                status = "okay";
                microsd-led {                                     /* 添加 microsd-led 节点 */
                    gpios = <&gpio3 RK_PC1 GPIO_ACTIVE_HIGH>;   /* 将 GPIO3_C1 注册为 microsd-led 的使能引脚，默认使能为电平拉高。 */
                    linux,default-trigger = "mmc1";             /* 设置默认触发器为 mmc1(SD Card) */
                };
            };
```
1. rsetup支持管理[任意一个gpio-leds](https://github.com/radxa-pkg/rsetup/blob/main/src/usr/lib/rsetup/cli/system.sh#L111-L117)，所以为了避免当前内核未定义gpio-leds节点的情况（多见于主线内核dts）最好是自己完整定义一个。
2. `default-state`的[理解有误](https://github.com/radxa/kernel/pull/227)

对齐和英文版本的修改麻烦处理一下，github网页不是很好操作这些

2023-10-18 05:29 UTC, CodeChenL commented on docs/general-tutorial/add-led.md
> +            };
我的写法，如果gpio-leds节点不存在不会创建吗

2023-10-18 06:21 UTC, RadxaYuntian commented on docs/general-tutorial/add-led.md
> +            };
会创建，但是少了compatible和status属性，系统不会为这个节点加载对应驱动

2023-10-18 06:21 UTC, RadxaYuntian approved these changes

2023-10-18 06:28 UTC, merged