添加 使用 radxa/overlays 官方设备树插件教程
radxa-docs/documentation pull request #271
Opened 2023-10-21 20:45 UTC by CodeChenL

new file:   static/img/general-tutorial/radxa_overlays.webp

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-10-22 10:40 UTC, CodeChenL commented
review没问题再添加翻译

2023-10-26 07:02 UTC, RadxaYuntian commented
本地编译dts或者直接安装编译好的dtbo都可以通过rsetup完成：https://github.com/radxa-pkg/rsetup/blob/main/src/usr/lib/rsetup/tui/overlay/overlay.sh#L285

2023-10-26 08:15 UTC, CodeChenL commented
了解，那我改一下教程内容：直接用rsetup安装单个dts？

2023-10-26 08:41 UTC, RadxaYuntian commented
dts可以，如果是已经编译好的dtbo也是支持的

2023-10-26 08:43 UTC, CodeChenL commented
> dts可以，如果是已经编译好的dtbo也是支持的

我再加个预编译好的dtbo链接和提示dtbo也可以加载的info标签？

2023-10-26 08:46 UTC, RadxaYuntian commented
可以啊

2023-10-31 08:00 UTC, CodeChenL commented
@RadxaYuntian 请问有空review一下吗，没问题我就开始翻译

2023-10-31 08:05 UTC, RadxaYuntian requested changes
麻烦pull一下上游，然后补一下英文吧

2023-10-31 08:13 UTC, CodeChenL commented
> 麻烦pull一下上游，然后补一下英文吧

好的

2023-10-31 08:35 UTC, RadxaYuntian approved these changes

2023-10-31 08:49 UTC, CodeChenL commented
哪里出现了问题？

2023-10-31 09:03 UTC, merged