fix code style issue in os-installation.md
radxa-docs/documentation pull request #297
Opened 2023-10-31 09:50 UTC by peterwang2050

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-10-31 11:43 UTC, RadxaYuntian requested changes

2023-10-31 11:43 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/os-installation.md
目前要求是写中文文档，然后用机器翻译生成对应英文修改

2023-10-31 11:43 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
>  :::tip
```suggestion
:::tip
本教程适用于瑞莎官方镜像。


```
1. 用户不知道到底哪些第三方镜像是支持的，建议省去
2. 额外的安装说明可以放在tab内

2023-10-31 11:43 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
> +
```suggestion
```
单个#仅限标题使用

2023-10-31 11:43 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
> +[upgrade_tool](general-tutorial/rksdk/upgrade_tool)（可同时烧录多台设备)
```suggestion
  <TabItem value="DirectConection" label="直连写入">

:::caution
部分瑞莎产品支持通过 USB 线缆与电脑连接，直接写入安装在设备上的 eMMC 或者 SPI 存储设备。  
然而此类安装方式相较前述几种而言，较为繁琐，仅建议有经验的用户尝试使用。
:::

如果您的设备使用 Rockchip 芯片，可参考以下教程：

1. 我的电脑使用的是 Windows
   [rkdevtool](/general-tutorial/rksdk/rkdevtool)
2. 我的电脑使用的是 Linux / macOS
   [rkdeveloptool](/general-tutorial/rksdk/rkdeveloptool)
   [upgrade_tool](general-tutorial/rksdk/upgrade_tool)（可同时烧录多台设备）

不在此列出的设备不支持与电脑直接连接写入存储设备。

  </TabItem>
</Tabs>
```

2023-10-31 12:07 UTC, RadxaYuntian requested changes

2023-10-31 12:07 UTC, RadxaYuntian commented on docs/general-tutorial/os-installation.md
> +
```suggestion
```

2023-10-31 12:14 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/os-installation.md
@Maycides 更新一下吧。我的机器翻译限额用完了

2023-10-31 13:16 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/os-installation.md
线刷和原有的EMMC/SD/SSD不是一个级别，不要放在一起， 使用读卡器刷 EMMC / SD / SSD , 线刷 EMMC/SD/SSD 
是这样一个逻辑

2023-11-01 01:58 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/general-tutorial/os-installation.md
rockchip现在线刷不了sd或者emmc

2023-11-01 06:58 UTC, Maycides approved these changes

2023-11-03 09:08 UTC, closed without merging

2023-11-03 09:36 UTC, RadxaYuntian commented
这个没有合并进去就关闭了？

2023-11-03 09:41 UTC, RadxaYuntian commented
Superseded by #305