add ROCK 3B guide
radxa-docs/documentation pull request #299
Opened 2023-11-01 03:49 UTC by Maycides

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-11-01 06:20 UTC, RadxaYuntian requested changes

2023-11-01 06:20 UTC, RadxaYuntian commented on docs/rock3/rock3b/getting-started.md
> +sidebar_label: "上手指南"
```suggestion
```
sidebar_label可以删掉，这样会自动使用标题。之后会考虑把所有现有的都删掉，避免显示不一致

2023-11-01 06:20 UTC, RadxaYuntian commented on docs/rock3/rock3b/getting-started.md
> +# 开始使用 ROCK 3B
```suggestion
# 开始使用
```

2023-11-01 06:20 UTC, RadxaYuntian commented on docs/rock3/rock3b/getting-started.md
> +### 系统安装
```suggestion
## 系统安装
```

2023-11-01 06:27 UTC, peterwang2050 commented on docs/rock3/rock3b/index.md
> +|            无线             | 可额外选购 [Radxa Wireless Module A8](/accessories/wireless-a8)                                                       |
可额外选购 这个怎么理解？

2023-11-01 06:27 UTC, peterwang2050 commented on docs/rock3/rock3b/index.md
> +|           以太网            | 支持以太网供电 (PoE) 的千兆以太网：PoE 供电需要额外选购的 HAT                                                         |
千兆以太网，支持POE(需配合HAT配件使用)    这样写会不会好点

2023-11-01 06:27 UTC, peterwang2050 commented on docs/rock3/rock3b/index.md
> +|            电源             | USB PD, 支持 USB Type-C PD 2.0<br/>Qualcomm® Quick ChargeTM: 支持 QC 3.0/2.0 协议<br/>USB Type-C DC 供电             |
电压范围要标记下

2023-11-01 07:51 UTC, RadxaYuntian requested changes

2023-11-01 07:51 UTC, RadxaYuntian commented on docs/rock3/rock3b/index.md
目录这边的页面就约定用README.md吧，这样在github上面直接查看源代码的话也会自动显示出来

2023-11-02 06:16 UTC, RadxaYuntian commented
Conversation谁提的谁resolve,除非是应用代码建议自动resolve

2023-11-02 06:17 UTC, RadxaYuntian commented
@peterwang2050 还有review要用request change来阻止pr合入。我们现在的设定是只要一个approval就可以合入，所以像你之前review用comment的话是不会阻止合入的

2023-11-03 07:25 UTC, Maycides commented on docs/rock3/rock3b/README.md
> +|            无线             | 可额外选购 [Radxa Wireless Module A8](/accessories/wireless-a8)                                                                                                 |
```suggestion
|            无线             | [Radxa Wireless Module A8](/accessories/wireless-a8) 无线模组                                                                                                |
```

2023-11-03 07:36 UTC, peterwang2050 commented on docs/rock3/rock3b/README.md
> +|            电源             | USB PD, 支持 USB Type-C PD 2.0, 9V/2A, 12V/2A, 15V/2A, 20V/2A<br/>Qualcomm® Quick ChargeTM: 支持 QC 3.0/2.0 协议，9V/2A, 12V/1.5A<br/>USB Type-C DC 6~24V 供电 |
```suggestion
|            电源             | USB PD, 支持 USB Type-C PD 2.0, 9V/2A, 12V/2A, 15V/2A, 20V/2A<br/>Qualcomm® Quick ChargeTM: 支持 QC 3.0/2.0 协议，9V/2A, 12V/1.5A<br/>USB Type-C DC 5.3~12V 供电 |
```

2023-11-03 07:36 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/README.md
> +|            Power            | USB PD, support USB Type-C PD 2.0, 9V/2A, 12V/2A, 15V/2A, 20V/2A<br/>Qualcomm® Quick ChargeTM: support QC 3.0/2.0, 9V/2A, 12V/1.5A<br/>USB Type-C DC 6~24V power supply
```suggestion
|            Power            | USB PD, support USB Type-C PD 2.0, 9V/2A, 12V/2A, 15V/2A, 20V/2A<br/>Qualcomm® Quick ChargeTM: support QC 3.0/2.0, 9V/2A, 12V/1.5A<br/>USB Type-C DC 5.3~12V power supply |
```

2023-11-03 09:11 UTC, peterwang2050 approved these changes

2023-11-03 09:13 UTC, peterwang2050 approved these changes

2023-11-03 09:35 UTC, RadxaYuntian approved these changes

2023-11-03 09:44 UTC, merged