decoupled use-uart2-as-application-uart.md
radxa-docs/documentation pull request #303
Opened 2023-11-01 11:35 UTC by CodeChenL

###### Description of changes
关联 #187 

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-11-01 11:36 UTC, CodeChenL commented
zero3的系统镜像链接文档还没添加，是镜像还不完善还是没来得及添加？
如果是后者我可以帮忙添加

2023-11-01 11:37 UTC, RadxaYuntian requested changes

2023-11-01 11:37 UTC, RadxaYuntian commented on docs/radxa-os/development/use-uart2-as-application-uart.md
> +### 跟随[修改 Linux 启动参数](/radxa-os/config/cmdline)的操作，在进行 `sudo nano /etc/kernel/cmdline` 操作时，删除所有 ttyFIQ0 和 ttyS2 相关的 console 参数，如 "console=ttyFIQ0,1500000n8"
#是用来标记主标题/小标题的，会在页面右边的索引里面显示。不要用这个来进行文本格式化

2023-11-01 11:38 UTC, RadxaYuntian commented
镜像我们是确认发布后再更新的，所以要看我们内部的评估

2023-11-02 02:26 UTC, RadxaYuntian reviewed
可以先这样写吧。麻烦补充一下英文版本

2023-11-02 05:58 UTC, CodeChenL commented
> 可以先这样写吧。麻烦补充一下英文版本

好的

2023-11-02 06:22 UTC, RadxaYuntian approved these changes

2023-11-02 06:34 UTC, merged