add cm3i docs
radxa-docs/documentation pull request #337
Opened 2023-11-21 11:54 UTC by Radxa-Alvin

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-11-22 06:22 UTC, peterwang2050 commented on docs/compute-module/cm3i/accessories-guides/cm3i-io-board.md
> +- 1x 12V DC 引脚：提供直接 12V 电源 输入/输出 选项。
这个是12V 电源 输入/输出 选项吗 ？ 请确认下

2023-11-22 06:24 UTC, peterwang2050 commented on docs/compute-module/cm3i/accessories-guides/cm3i-io-board.md
> +- 14 个 GPIO 引脚：提供调试串口, Speak 和 headphone 接口
Speaker

2023-11-22 06:27 UTC, peterwang2050 commented on docs/compute-module/cm3i/getting-started.md
> +如果您想定制想要 CM3I 配置,欢迎您与瑞莎联系!
想要的CM3I配置

2023-11-22 06:35 UTC, peterwang2050 commented on docs/compute-module/cm3i/getting-started.md
> +- 内存：1GB, 2GB, 4GB or 8GB LPDDR4
上面写的配置是2/4/8/16G  ，你这里是1/2/4/8G

2023-11-22 06:42 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-system.md
> +   ![ROCK5A via Etcher 01](/img/rock5a/rock5a-etcher.webp)
这个工具和 板子类型强相关吗， 如果不相关就去掉，这里是CM3I ,写个ROCK 5A 不合适

2023-11-22 06:43 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/getting-started.md
> +## [Install System](/compute-module/cm3i/install-system)
由于还有其他Android系统，这个用install-debian-system 来代替

2023-11-22 06:45 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-system.md
> +3. Download corresponding product of the official Ubuntu / Debian system image
我们不维护Ubuntu，这里不要写出俩，另外这里看能否用链接链接到镜像下载页面

2023-11-22 06:47 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-system.md
> +
In the Ether window ?  没写全？

2023-11-22 06:52 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-system.md
> +6. In the Etcher window, `Flash Complete!` will be displayed when the swipe is successful
`Flash Complete!` will show when the flashing is completed

2023-11-22 06:53 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-system.md
> +
incorrently => fail

2023-11-22 07:03 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-system.md
> +
Swipe -> Flash

2023-11-22 07:04 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-system.md
> +
wait for the writing to be completed

2023-11-22 07:07 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-system.md
> +
so you need only to make the microSD / eMMC / SPI Flash unable to boot. 即可，后面删除

2023-11-22 07:13 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-system.md
> +2. Simultaneously press and hold the Maskrom Button SPI Flash and Maskrom Button eMMC buttons on the CM3I
MaskROM Button SPI Flash 修改下这个词，看不懂什么意思，  还有这个Maskrom Button emmc buttons  ，emmc buttons 是 button 还是buttons

2023-11-22 07:24 UTC, peterwang2050 requested changes

2023-11-22 07:24 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-system.md
> +rkdeveloptool can be thought of as [upgrade_tool](/general-tutorial/rksdk/upgrade_tool) for [open source version](https://opensource.rock-chips.com/wiki_Rkdeveloptool).
can be thought of ?

2023-11-22 07:24 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/install-system.md
> +
If there is no rkdeveloptool version for your operate system, you will need to compile it from source and then install it

2023-11-23 12:21 UTC, peterwang2050 commented on docs/compute-module/cm3i/getting-started.md
> +- 内存：1GB, 2GB, 4GB or 8GB LPDDR4
目前 SKU，
RAM： 2 / 4 / 8
EMMC: 8 / 16 / 32 
没有的SKU，暂时先不写吧

2023-11-23 12:33 UTC, peterwang2050 commented on docs/compute-module/cm3i/getting-started.md
> +- 内存：1GB, 2GB, 4GB or 8GB LPDDR4
RAM:1/2/4/8G
EMMC: 8/16/32/64/128G
和这里保持一致 https://radxa.com/products/compute-module/cm3i/

2023-11-23 12:34 UTC, peterwang2050 commented on docs/compute-module/cm3i/getting-started.md
> +  - eMMC5.1 8GB / 16GB / 32GB / 64GB, eMMC 最大可达 512GB
最大 512G 数据从哪里来的？

2023-11-24 07:11 UTC, peterwang2050 commented on docs/compute-module/images.md
> +
这段删除，除了Debian，我们还有Android，Yocto，官方出的测试的版本，都是官方镜像，不仅仅是Debian

2023-11-24 07:16 UTC, peterwang2050 commented on docs/compute-module/cm3i/install-debian-system.md
> +3. 保持步骤 2 中的 Maskrom 按钮按下,接入电源,即可进入 MASKROM 模式
同时按住 SPI Flash 的 Maskrom 按键  和 eMMC 的 Maskrom 按键并保持

2023-11-24 07:47 UTC, Radxa-Alvin commented on docs/compute-module/cm3i/install-debian-system.md
> +3. 保持步骤 2 中的 Maskrom 按钮按下,接入电源,即可进入 MASKROM 模式
这两个按钮的命名跟图片是对应的  特意放了个图片就是为了给用户对照着看  建议不要修改

2023-11-24 07:54 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/getting-started.md
> +  - eMMC5.1 NA / 8GB / 16GB / 32GB / 64GB, eMMC Maximum 512GB
Maximum 256GB

2023-11-24 07:55 UTC, peterwang2050 commented on docs/compute-module/cm3i/getting-started.md
> +  - eMMC5.1 8GB / 16GB / 32GB / 64GB, eMMC 最大可达 512GB
最大256GB

2023-11-29 00:45 UTC, peterwang2050 approved these changes

2023-11-29 00:51 UTC, merged