update radxa zero3 docs
radxa-docs/documentation pull request #395
Opened 2023-12-19 07:40 UTC by Radxa-Alvin

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2023-12-19 11:26 UTC, akgnah approved these changes

2023-12-19 11:27 UTC, RadxaYuntian requested changes
没弄完

2023-12-19 11:27 UTC, RadxaYuntian commented on docs/zero/zero3/accessories/camera.md
> +# Camera
中文文章标题也要用中文

2023-12-19 11:27 UTC, RadxaYuntian commented on docs/zero/zero3/accessories/camera.md
> +## Radxa ZERO 3 CSI 接口定义
```suggestion
## CSI 接口定义
```

当前内容是zero 3章节的一部分，可以在标题中省去

2023-12-19 11:27 UTC, RadxaYuntian commented on docs/zero/zero3/accessories/camera.md
>  ![zero3w csi1 ](/img/zero/zero3w/zero3w-csi1.webp)
```suggestion
![zero3w csi1](/img/zero/zero3w/zero3w-csi1.webp)
```

2023-12-19 11:27 UTC, RadxaYuntian commented on docs/zero/zero3/application-configuration/samba.md
> +sudo apt install samba
```suggestion
sudo apt-get update
sudo apt-get install samba
```
apt的CLI是不稳定的，用apt-get

2023-12-19 11:27 UTC, RadxaYuntian commented on docs/zero/zero3/application-configuration/samba.md
> +
```suggestion

Samba 是 Linux 下常用的 SMB/CIFS 工具。通过 Samba ，您可以和包含 Windows 和 Android 在内的多种不同操作系统间进行文件分享。

## 安装 Samba

```

文章需要有个简介，然后正文分节：安装、配置

2023-12-19 11:27 UTC, RadxaYuntian commented on docs/zero/zero3/application-configuration/samba.md
> +sudo vim /etc/samba/smb.conf
```suggestion
sudo nano /etc/samba/smb.conf
```
默认使用nano进行文本编辑，不然用户都不知道怎么退出

2023-12-19 11:27 UTC, RadxaYuntian commented on docs/zero/zero3/application-configuration/samba.md
> +comment=zero3 share
```suggestion
[radxa]
comment=Shared from my Radxa device
```
同一个文章可以在不同产品中引用，避免在配置中使用产品名

2023-12-19 11:35 UTC, RadxaYuntian requested changes
英文也要同步修改

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/application-configuration/samba.md
> +sudo chmod 755 /mnt/samba
```suggestion
sudo mkdir /media/samba
sudo chmod 755 /media/samba
```
/mnt目录一般会被用户使用挂载临时磁盘，持久储存用/media好一点

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/application-configuration/samba.md
> +6. 启动 Samba 服务
```suggestion
6. 重新启动 Samba 服务以加载更新后的配置
```

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/getting-started/accessory-usage.md
> +![zero-3w-interface-overview ](/img/zero/zero3w/zero-3w-interface-overview.webp)
```suggestion
![zero-3w-interface-overview](/img/zero/zero3w/zero-3w-interface-overview.webp)
```

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/getting-started/accessory-usage.md
> +### Radxa ZERO 3W 接口总览
这里可以用tab

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/getting-started/accessory-usage.md
> +![zero-3e-interface-overview ](/img/zero/zero3w/zero-3e-interface-overview.webp)
```suggestion
![zero-3e-interface-overview](/img/zero/zero3w/zero-3e-interface-overview.webp)
```

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/getting-started/accessory-usage.md
> +Radxa ZERO 3W/3E 带有一个 22PIN 的 CSI 接口。[Camera 使用教程](/zero/zero3/accessories/camera.md)
```suggestion
Radxa ZERO 3 带有一个 22-pin 的 CSI 接口。更多信息请参见[摄像头使用教程](/zero/zero3/accessories/camera.md)
```

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/getting-started/install-os.md
> +- **ZERO 3W**
tab

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/getting-started/install-os.md
> +- 按照上述步骤成功烧录 microSD 卡后，将 microSD 卡接入 Radxa ZERO 3W/3E 的 `Micro SD Card Slot` 座子上
```suggestion
- 按照上述步骤成功烧录 microSD 卡后，将 microSD 卡插入 Radxa ZERO 3 的 `Micro SD Card Slot` 插槽内
```

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/getting-started/install-os.md
> +- Radxa ZERO 3W/3E 的供电接口为 `USB 2.0 OTG Type C port`，使用 Type C 线缆连接供电口和适配器
```suggestion
- Radxa ZERO 3 的供电接口为 `USB 2.0 OTG Type C port`，请使用 Type-C 线缆连接供电口和适配器
```

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/getting-started/install-os.md
> +Radxa ZERO 3W/3E只支持 `5V` 供电,瑞莎推荐使用 [Radxa Power PD30W](/accessories/pd_30w)
```suggestion
Radxa ZERO 3 只支持 `5V` 供电。瑞莎推荐使用 [Radxa Power PD30W](/accessories/pd_30w)。
```

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/lowlevel-development/maskrom-flash.md
> +Radxa ZERO 3e 进入 Maskrom 模式的方法
```suggestion
Radxa ZERO 3E 进入 Maskrom 模式的方法
```

2023-12-19 11:35 UTC, RadxaYuntian commented on docs/zero/zero3/lowlevel-development/maskrom-flash.md
> +- **ZERO 3W**
tab

2023-12-20 08:41 UTC, RadxaYuntian requested changes
英文也要同步

2023-12-20 08:41 UTC, RadxaYuntian commented on docs/zero/zero3/accessories/camera.md
> +![zero3w csi](/img/zero/zero3w/zero3w-csi.webp)
怎么重复了两遍，文件名也不同？

2023-12-20 08:41 UTC, RadxaYuntian commented on docs/zero/zero3/accessories/camera.md
>  sudo rsetup
```suggestion
rsetup
```

2023-12-20 08:41 UTC, RadxaYuntian commented on docs/zero/zero3/accessories/camera.md
>  执行指令，开始读秒后按下 `ctrl + C`即可拍照, 照片路径为 `/home/radxa/test.jpg`
```suggestion
执行指令，开始读秒后按下 `Ctrl + C`即可拍照, 照片路径为 `/home/radxa/test.jpg`
```

2023-12-20 08:41 UTC, RadxaYuntian commented on docs/zero/zero3/application-configuration/samba.md
> +writable=yes
```suggestion
comment = Shared from my Radxa device
path = /media/samba
available = yes
valid users = radxa
public = yes
writable = yes
```

2023-12-20 08:41 UTC, RadxaYuntian commented on docs/zero/zero3/application-configuration/samba.md
> +sudo service smbd restart
```suggestion
sudo systemctl restart smbd
```
systemctl更通用

2023-12-20 09:05 UTC, Radxa-Alvin commented on docs/zero/zero3/accessories/camera.md
> +![zero3w csi](/img/zero/zero3w/zero3w-csi.webp)
两种不同的图片

2023-12-20 09:06 UTC, Radxa-Alvin commented on docs/zero/zero3/accessories/camera.md
>  sudo rsetup
rsetup 不是需要sudo 权限么

2023-12-20 09:20 UTC, RadxaYuntian commented on docs/zero/zero3/accessories/camera.md
>  sudo rsetup
会按照用户所在的环境自动调用不同的提权命令

2023-12-20 09:23 UTC, RadxaYuntian requested changes

2023-12-20 09:23 UTC, RadxaYuntian commented on docs/zero/zero3/getting-started/accessory-usage.md
> +Radxa ZERO 3W 接口总览
```suggestion
```

2023-12-20 09:23 UTC, RadxaYuntian commented on docs/zero/zero3/getting-started/accessory-usage.md
> +	<TabItem value="ZERO 3E">
```suggestion
<TabItem value="ZERO 3E">
```

2023-12-20 09:23 UTC, RadxaYuntian commented on docs/zero/zero3/getting-started/accessory-usage.md
> +</TabItem>
```suggestion
![zero-3e-interface-overview](/img/zero/zero3w/zero-3e-interface-overview.webp)

</TabItem>
```

2023-12-20 09:23 UTC, RadxaYuntian commented on docs/zero/zero3/lowlevel-development/maskrom-flash.md
> +  ![ZERO 3W Overview](/img/zero/zero3w/radxa_zero_3w.webp)
```suggestion
![ZERO 3W Overview](/img/zero/zero3w/radxa_zero_3w.webp)
```

2023-12-20 09:23 UTC, RadxaYuntian commented on docs/zero/zero3/lowlevel-development/maskrom-flash.md
> +  ![ZERO 3E Overview](/img/zero/zero3w/radxa_zero_3e.webp)
```suggestion
![ZERO 3E Overview](/img/zero/zero3w/radxa_zero_3e.webp)
```

2023-12-20 12:05 UTC, RadxaYuntian approved these changes

2023-12-20 12:15 UTC, merged