Update deploy.yaml
radxa-docs/documentation pull request #556
Opened 2024-02-05 03:42 UTC by CodeChenL

###### Description of changes
关联#348

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2024-02-05 03:43 UTC, CodeChenL commented
test

2024-02-05 03:44 UTC, CodeChenL commented
Test comment by

2024-02-05 03:48 UTC, RadxaYuntian commented
把CI里面的gh pr comment注释删除，然后手动在if条件外面执行一次看看能不能添加pr comment

2024-02-05 03:49 UTC, RadxaYuntian commented
这个需要你先commit到你自己的仓库里面，再生成一个pr触发，因为pull_request_target是在pr修改之前的head里面执行的

2024-02-05 04:00 UTC, CodeChenL commented
> 这个需要你先commit到你自己的仓库里面，再生成一个pr触发，因为pull_request_target是在pr修改之前的head里面执行的

需要一个其他账号提交test PR，你可以尝试在我的仓库提交一下pr吗

2024-02-05 06:41 UTC, RadxaYuntian commented
你后面的代码都要改，现在是没有对这个新事件有处理的

2024-02-05 08:15 UTC, CodeChenL commented
@RadxaYuntian https://github.com/CodeChenL/documentation/pull/8 现在这种状态可以吗，需不需要给trigger pull request也检查超长链接

2024-02-05 08:58 UTC, RadxaYuntian commented on .github/workflows/deploy.yaml
> +              FROM_REF="${{ github.event.pull_request_target.base.sha }}"
没有这个payload吧？

2024-02-05 09:07 UTC, RadxaYuntian commented
你之前不是说payload里面的ref不对么？现在看来是没问题的？

2024-02-05 09:10 UTC, CodeChenL commented
> 你之前不是说payload里面的ref不对么？现在看来是没问题的？

没有吧https://github.com/CodeChenL/documentation/actions/runs/7781877825/job/21217175004#step:3:172的echo extarg是空的

2024-02-05 10:02 UTC, RadxaYuntian commented on .github/workflows/deploy.yaml
> +          if [[ -z "${{ matrix.test }}" && ${{ github.event_name }} == "pull_request" ]] || [[ ! -z "${{ matrix.test }}" && ${{ github.event_name }} == "pull_request_target" ]]
应该是在job.test.if这里做处理，跳过不需要的配置，而不是在shell里面再去判断

2024-02-05 10:18 UTC, RadxaYuntian requested changes

2024-02-05 10:18 UTC, RadxaYuntian commented on .github/workflows/deploy.yaml
> +            git merge "$FROM_REF" "$TO_REF"
你看上面45行啊，直接把没有的commit fetch回来，不要操作分支啊

2024-02-05 10:35 UTC, RadxaYuntian commented on .github/workflows/deploy.yaml
> +            git checkout "$TO_REF"
不用checkout应该也可以运行pre-commit的

2024-02-05 10:51 UTC, CodeChenL commented on .github/workflows/deploy.yaml
> +            git checkout "$TO_REF"
已测试需要checkout

2024-02-05 10:55 UTC, CodeChenL commented
测试结果https://github.com/CodeChenL/documentation/pull/17

2024-02-05 11:49 UTC, RadxaYuntian requested changes

2024-02-05 11:49 UTC, RadxaYuntian commented on .github/workflows/deploy.yaml
> +            fi
为什么这里改了缩进？

2024-02-05 11:49 UTC, RadxaYuntian commented on .github/workflows/deploy.yaml
> +          git checkout "$TO_REF"
你试过在pull_request_target那边添加github.event.pull_request.head.repo.url作为remote，再fetch对应的ref么？另外先不要重构别的代码逻辑（push那边）

2024-02-05 11:57 UTC, CodeChenL commented on .github/workflows/deploy.yaml
> +            fi
把if判断移到上面了

2024-02-05 12:12 UTC, CodeChenL commented on .github/workflows/deploy.yaml
> +          git checkout "$TO_REF"
https://github.com/CodeChenL/documentation/actions/runs/7784175275/job/21224201083?pr=18#step:3:28

2024-02-05 12:12 UTC, CodeChenL commented on .github/workflows/deploy.yaml
> +          git checkout "$TO_REF"
地址不对

2024-02-05 12:17 UTC, RadxaYuntian commented on .github/workflows/deploy.yaml
> +          git checkout "$TO_REF"
https://docs.github.com/en/webhooks/webhook-events-and-payloads#pull_request
把payload打印一份看看哪个才是正确的咯

2024-02-05 12:40 UTC, RadxaYuntian commented
突然发现我们只要不让这个check作为required就可以了……

2024-02-06 01:48 UTC, CodeChenL commented
> 突然发现我们只要不让这个check作为required就可以了……

你的意思是在pre-commit设置这个check不是必须的吗，可是不还是有pull_request_target没有同步代码的问题

2024-02-06 02:38 UTC, CodeChenL commented
测试效果https://github.com/CodeChenL/documentation/pull/26

2024-02-06 03:15 UTC, RadxaYuntian requested changes

2024-02-06 03:15 UTC, RadxaYuntian commented on .github/workflows/deploy.yaml
> +  check-external-links:
```suggestion
  test-optional:
```

2024-02-06 03:17 UTC, RadxaYuntian requested changes

2024-02-06 03:17 UTC, RadxaYuntian commented on .github/workflows/deploy.yaml
> +      GH_TOKEN: ${{ github.token }}
```suggestion
```
test那边也要删除。这是给gh pr用的

2024-02-06 03:25 UTC, RadxaYuntian requested changes
改完重写一下历史

2024-02-06 03:25 UTC, RadxaYuntian commented on .github/workflows/deploy.yaml
> +
```suggestion

          if [[ ! -z "${{ matrix.test }}" ]]
          then
            EXTRA_ARGS+=("--hook-stage" "manual" "${{ matrix.test }}")
          fi

```
复制就是字面意义上的复制啊，咋还少东西了

2024-02-06 03:31 UTC, RadxaYuntian approved these changes

2024-02-06 03:53 UTC, merged