feat: add CODEOWNERS
radxa-docs/documentation pull request #598
Opened 2024-02-23 07:52 UTC by CodeChenL

* revised https://github.com/radxa-docs/documentation/issues/596

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2024-02-23 08:00 UTC, RadxaYuntian requested changes
1. issue里面说了要有codeowners coverage，没有
2. 有了coverage ci就会知道.github没有owner
3. 前端加上 @xzuoqi

2024-02-23 08:01 UTC, CodeChenL commented
好的，还是草稿状态

2024-02-23 09:43 UTC, RadxaYuntian requested changes

2024-02-23 09:43 UTC, RadxaYuntian commented on .github/CODEOWNERS
> +**/x
```suggestion
**/x                @shawnchainw
```
这样加上去后会不会在重新运行gitown时清除掉？

2024-02-23 09:46 UTC, CodeChenL commented on .github/CODEOWNERS
> +**/x
gitown只会在末尾添加单个文件的owner

2024-02-23 09:51 UTC, RadxaYuntian commented on .github/CODEOWNERS
> +**/x
文件开头的注释是它添加的么？如果可以最好在我们人工设置的规则和后面自动添加的规则中间加一个注释行分割一下

2024-02-26 01:22 UTC, CodeChenL commented on .github/CODEOWNERS
> +**/x
开头注释是gitown添加的，一开始的提交有用注释分类，但是都被gitown给格式化了

2024-02-26 06:32 UTC, RadxaYuntian commented on .github/CODEOWNERS
> +.github             @RadxaYuntian
```suggestion
.github             @RadxaYuntian

# Rules generated by gitown

```

2024-02-26 06:35 UTC, RadxaYuntian commented
另外可能要关注一下为什么有“No hook with id `check-external-links` in stage `manual`”报错

2024-02-26 10:17 UTC, closed without merging