feat: add CODEOWNERS
radxa-docs/documentation pull request #603
Opened 2024-02-26 10:36 UTC by CodeChenL

###### Description of changes
* revised https://github.com/radxa-docs/documentation/issues/596

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2024-02-26 11:41 UTC, RadxaYuntian commented
原来的pr可以reopen的，现在审查历史都没了

2024-02-26 11:42 UTC, CodeChenL commented
> 原来的pr可以reopen的，现在审查历史都没了

我试过了，是灰色的

2024-02-26 11:43 UTC, RadxaYuntian requested changes

2024-02-26 11:43 UTC, RadxaYuntian commented on .github/CODEOWNERS
> +static              @xzuoqi @akgnah # setq@radxa.com
邮箱注释删掉，加上分割线注释

2024-02-27 02:52 UTC, RadxaYuntian reviewed
重写历史

2024-02-27 03:33 UTC, RadxaYuntian requested changes

2024-02-27 03:33 UTC, RadxaYuntian commented on .github/CODEOWNERS
> +**/rock5itx         @yjxyx # liuxian@radxa.com
```suggestion
**/rock5itx         @yjxyx
```

2024-02-27 03:36 UTC, RadxaYuntian requested changes

2024-02-27 03:36 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +          ]
```suggestion
```
这些保持默认就好。
确认一下删掉后precommit hook仍然可以正确找到codeowner文件

2024-02-27 03:41 UTC, RadxaYuntian reviewed
确认没问题再重写一下历史

2024-02-27 03:42 UTC, RadxaYuntian commented
哦测试失败了，要指定CODEOWNERS的位置
还是放在.github里面

2024-02-27 03:43 UTC, RadxaYuntian reviewed
squash

2024-02-27 04:03 UTC, RadxaYuntian approved these changes

2024-02-27 04:11 UTC, merged