Add commit check
radxa-docs/documentation pull request #604
Opened 2024-02-26 10:57 UTC by CodeChenL

###### Description of changes
* close https://github.com/radxa-docs/pre-commit-hooks/issues/4
* close https://github.com/radxa-docs/pre-commit-hooks/issues/5

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2024-02-26 11:10 UTC, CodeChenL commented
效果见https://github.com/CodeChenL/documentation/pull/1

2024-02-26 11:50 UTC, RadxaYuntian requested changes

2024-02-26 11:50 UTC, RadxaYuntian commented on .github/workflows/deploy.yaml
>            if [[ ! -z "${{ matrix.test }}" ]]
我们要求test和test-optional的代码保持同步，所以上面的matrix可以加一个`stage: ["commit", "push", "manual"]`。然后两个测试对应的stage不同

2024-02-27 02:55 UTC, RadxaYuntian reviewed
重写历史

2024-02-27 06:30 UTC, CodeChenL commented
已压缩commit

2024-02-27 06:37 UTC, CodeChenL commented
修复合并冲突又多了一个commit.。。。

2024-02-27 07:24 UTC, RadxaYuntian commented
CI挂了：https://github.com/radxa-docs/documentation/actions/runs/8060733327/job/22017250618?pr=604#step:3:199

2024-02-27 07:25 UTC, RadxaYuntian commented
怎么会有gitown的ci

2024-02-27 07:27 UTC, CodeChenL commented
> 怎么会有gitown的ci

gitown的pr合并了呀

2024-02-27 07:27 UTC, CodeChenL commented
这条commit需要压缩不https://github.com/radxa-docs/documentation/pull/604/commits/fa22505629c2695edb963446fc3c9f2048709574

2024-02-27 07:30 UTC, RadxaYuntian commented
两个不是一件事就不用

2024-02-27 07:31 UTC, RadxaYuntian reviewed
两个commit顺序调换，另外现在第二个commit的类型应该是fix

2024-02-27 07:42 UTC, RadxaYuntian approved these changes

2024-02-27 07:52 UTC, merged