fix: change gitown stages
radxa-docs/documentation pull request #612
Opened 2024-02-29 03:18 UTC by CodeChenL

###### Description of changes
* fixes https://github.com/radxa-docs/documentation/pull/611 CI check error

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2024-02-29 03:19 UTC, CodeChenL commented on .github/CODEOWNERS
> +.pre-commit-config.* @CodeChenL @RadxaYuntian
这里的修改是因为，gitown会把@RadxaYuntian去除

2024-02-29 03:23 UTC, CodeChenL commented
上次是我记错了应该，现在应该是自动request codeowner 来 review

2024-02-29 03:24 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +          - pre-push
commit以及push阶段吧。现在的问题是不是一些在安装hook之前的commit被漏掉了？

2024-02-29 03:26 UTC, CodeChenL commented on .pre-commit-config.yaml
> +          - pre-push
现在好像是，默认在pre-commit阶段运行。导致commit还没应用，所以check不出来

2024-02-29 03:27 UTC, CodeChenL commented on .pre-commit-config.yaml
> +          - pre-push
不过我加了post-commit也没效果，就pre-push有效果

2024-03-01 02:41 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +          - pre-push
> 一直调换两个codeowner的前后位置
是不是修改没有stage进去？没有stage的话应该是不会被ci处理的

2024-03-01 02:43 UTC, CodeChenL commented on .pre-commit-config.yaml
> +          - pre-push
> > 一直调换两个codeowner的前后位置
> > 是不是修改没有stage进去？没有stage的话应该是不会被ci处理的

是在本地运行commit出现的

2024-03-01 03:08 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +          - pre-push
就是应该首先commit，然后gitown提示修改，再stage gitown提示的修改，最后commit

2024-03-04 07:42 UTC, RadxaYuntian requested changes

2024-03-04 07:42 UTC, RadxaYuntian commented on .github/CODEOWNERS
> +.pre-commit-config.yaml @CodeChenL
上面通配符匹配这里怎么还是有重复录入？

2024-03-04 07:42 UTC, RadxaYuntian commented on i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/heatsink-4012.md
这些要split pr

2024-03-04 07:43 UTC, CodeChenL commented on .github/CODEOWNERS
> +.pre-commit-config.yaml @CodeChenL
gitown识别不了我们手动写的带通配符的codeowner

2024-03-04 07:46 UTC, CodeChenL commented on i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/heatsink-4012.md
这些是我合并上游检查出来的，不解决push不了

2024-03-04 07:47 UTC, RadxaYuntian commented
冲突修复一下，然后把相关commit squash

2024-03-04 08:35 UTC, RadxaYuntian approved these changes

2024-03-04 08:44 UTC, merged