add Docs zero
radxa-docs/documentation pull request #624
Opened 2024-03-05 11:18 UTC by CodeChenL

###### Description of changes

###### Review guide

To review this PR locally, please run the following commands:

```bash
PR= # the current PR number
git fetch origin pull/${PR}/head
git switch --detach FETCH_HEAD
yarn start
yarn start --locale en
# If you want to start 2 locales side-by-side, use the following command on Linux:
# https://github.com/facebook/docusaurus/issues/7377#issuecomment-1167192715
yarn start & DOCUSAURUS_GENERATED_FILES_DIR_NAME=.docusaurus/en yarn start --locale en --port 3001
kill %1
```

2024-03-05 13:08 UTC, peterwang2050 commented on docs/zero/zero/getting-started/preparation.md
> +Radxa ZERO 的功耗比较低，可以直接使用电脑USB供电，所以不再需要准备单独的电源适配器。如果独立使用Radxa ZERO，可以使用 5V，1A（至少）的电源适配器。
你只需要告知使用什么样的电源供电即可，不需要为客户考虑那么多，客户使用的场景很多样，请重新组织下语言

2024-03-05 13:10 UTC, peterwang2050 commented on docs/zero/zero/getting-started/preparation.md
> +如果开发板没有板载eMMC需要准备一个至少8GB的sd卡. eMMC是板子背面的那个大的贴片芯片，你可以检查下你的板子是否有这个元件。
什么背面的打的贴片芯片，这个用户怎么知道，请用准备的语言或者图片索引来标记，另外太口语话，太啰嗦，请精简语言

2024-03-05 13:11 UTC, peterwang2050 commented on docs/zero/zero/getting-started/preparation.md
> +Radxa ZERO 有一个板载 Type-C USB3.0接口（靠近板子中间的那个USBC口）。这个接口支持通过 USB Type-C hub 转出 Type-A 口和有线网(如果 hub 支持)，但是不具备视频输出功能。
靠近板子中间的那个USB口，直接使用图片索引的方式，链接到 标记图中

2024-03-06 02:00 UTC, CodeChenL commented
大部分内容是copy之前用户贡献的页面所以会比较口语化，我改一下

2024-03-08 11:31 UTC, peterwang2050 commented on docs/zero/zero/README.md
> +        <td align="center">板载一颗 ap6212/ap6256/aw-cm256sm WIFI/BT 模块</td>
直接写 wifi模块型号就行，不用加 “板载一颗” 这些

2024-03-08 11:40 UTC, peterwang2050 commented on docs/zero/zero/README.md
> +        <td colspan="2" align="center">提供 Micro HDMI 接口：支持 1080p60 输出</td>
Micro HDMI x 1，1080p60

2024-03-08 12:15 UTC, RadxaYuntian commented on docs/zero/zero/README.md
> +        <td colspan="2" align="center">提供 Micro HDMI 接口：支持 1080p60 输出</td>
Android是支持4K60p的。但Linux的驱动有问题，只能在4K30p模式下显示

2024-03-11 07:38 UTC, peterwang2050 commented on docs/zero/zero/getting-started/install-os.md
> +  - 推荐使用官方的 Radxa Power PD 30W 。<img src="/img/accessories/pd-30w.webp" alt="Radxa Power PD 30W" width="300" />
Radxa Power PD 30w  可以作为链接，链接到对应的配件中

2024-03-11 08:06 UTC, peterwang2050 commented on docs/zero/zero/getting-started/preparation.md
> +如果开发板没有板载 eMMC 则需要准备一个至少 8GB 的 sd 卡。[eMMC 位于开发板背面](../hardware-design/hardware-interface#接口总览)，您可以检查一下您的开发板是否具有这个元件。
这个排版有问题，你可以运行后看一下效果。另外 关于  EMMC 位于开发板背面 这段解释，可以用（）括起来

2024-03-11 08:07 UTC, peterwang2050 commented on docs/zero/zero/hardware-design/hardware-interface.md
> +推荐使用官方的 Radxa Power PD 30W 。<img src="/img/accessories/pd-30w.webp" alt="Radxa Power PD 30W" width="300" />
放在 Radxa Power PD 30w 在配件中的链接

2024-03-11 08:22 UTC, peterwang2050 commented on docs/zero/zero/low-level-dev/install-os-on-emmc.md
> +请按以下步骤进入 Maskrom 模式：
maskrom 这个应该是rk的叫法，这里是amlogic平台，看下amlogic平台怎么定义，没有的话，就写进入刷机模式

2024-03-11 08:22 UTC, peterwang2050 commented on docs/zero/zero/low-level-dev/install-os-on-emmc.md
> +
maskrom 修改，同上

2024-03-11 08:35 UTC, peterwang2050 commented on docs/zero/zero/getting-started/download.md
> +更多镜像请查看： [Radxa ZERO Release](https://github.com/radxa-build/radxa-zero/releases)
这里是不是相比wiki有删减，把这些第三方镜像 放到  other-os 目录下，这里用个链接链过去，

2024-03-11 08:39 UTC, peterwang2050 commented on docs/zero/zero/getting-started/install-os.md
> +  - HDMI EDID用于确定最佳显示分辨率。 在支持 1080p 的显示器和电视上，将选择此分辨率。 如果不支持 1080p，EDID会找到的下一个可用分辨率。 此选定模式适用于大多数显示器/电视，但不适用于所有显示器/电视。
这里不用介绍EDID， 这些文档是为小白写的，尽量降低理解的复杂度

2024-03-11 08:39 UTC, peterwang2050 commented on docs/zero/zero/getting-started/install-os.md
> +  - HDMI EDID用于确定最佳显示分辨率。 在支持 1080p 的显示器和电视上，将选择此分辨率。 如果不支持 1080p，EDID会找到的下一个可用分辨率。 此选定模式适用于大多数显示器/电视，但不适用于所有显示器/电视。
这里不用介绍EDID， 这些文档是为小白写的，尽量降低理解的复杂度

2024-03-11 08:40 UTC, peterwang2050 commented on docs/zero/zero/getting-started/install-os.md
> +ZERO 支持 5V 电源输入。瑞莎推荐使用 [Radxa Power PD30W](../accessories/pd-30w)。
这里可能要说下，对电流的要求，比如至少需要 5V 2A

2024-03-11 08:43 UTC, peterwang2050 commented on docs/zero/zero/other-os/android/preparation.md
> +如果开发板没有板载 eMMC 则需要准备一个至少 8GB 的 sd 卡. [eMMC 位于开发板背面](../../hardware-design/hardware-interface#接口总览)，您可以检查一下您的开发板是否具有这个元件。
这里改动参考前面的评论

2024-03-11 08:44 UTC, peterwang2050 commented on docs/zero/zero/radxa-os/README.md
> +## 聊天视频
没有的项，就删除

2024-03-11 08:46 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero/getting-started/download.md
> +### 1.3 Final prototype version
V1.3 (Final prototype version)  按这样写

2024-03-11 08:50 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero/getting-started/accessory-usage.md
> +<img src="/img/zero/zero/zero-block-digram.webp" width="800" alt="zero interfaces overview" />
把常见的屏  / camera / wifi 列在这里

2024-03-11 08:50 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero/getting-started/accessory-usage.md
> +<img src="/img/zero/zero/zero-block-digram.webp" width="800" alt="zero interfaces overview" />
参考rock 5b

2024-03-11 08:52 UTC, peterwang2050 commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero/hardware-design/hardware-interface.md
> +
最好用表格的形式列出，将细节列出来，这部分可以放到 getting-started 配件使用中写，然后链接过去

2024-03-11 08:57 UTC, peterwang2050 requested changes
先改一下，等修完后再review一次，太多了

2024-03-11 09:01 UTC, CodeChenL commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero/getting-started/accessory-usage.md
> +<img src="/img/zero/zero/zero-block-digram.webp" width="800" alt="zero interfaces overview" />
zero没有没有屏幕、摄像头、wifi接口

2024-03-11 10:56 UTC, CodeChenL commented on docs/zero/zero/low-level-dev/install-os-on-emmc.md
> +请按以下步骤进入 Maskrom 模式：
刷机工具显示是Maskrom

2024-03-11 10:57 UTC, CodeChenL commented on docs/zero/zero/getting-started/download.md
> +更多镜像请查看： [Radxa ZERO Release](https://github.com/radxa-build/radxa-zero/releases)
删减了链接失效的系统

2024-03-11 11:00 UTC, CodeChenL commented on docs/zero/zero/getting-started/install-os.md
> +ZERO 支持 5V 电源输入。瑞莎推荐使用 [Radxa Power PD30W](../accessories/pd-30w)。
可是你在上一次review不是说，不需要吗

2024-03-11 11:08 UTC, CodeChenL commented on i18n/en/docusaurus-plugin-content-docs/current/zero/zero/hardware-design/hardware-interface.md
> +
这不是可插拔的wifi模块不属于配件把

2024-03-12 09:57 UTC, peterwang2050 commented on docs/zero/zero/getting-started/install-os.md
> +ZERO 支持 5V 电源输入。瑞莎推荐使用 [Radxa Power PD30W](../accessories/pd-30w)。
Radxa ZERO 的功耗比较低，可以直接使用电脑USB供电，所以不再需要准备单独的电源适配器.

我上面说的是这个， 很多客户使用场景不是电脑USB供电

2024-03-18 12:56 UTC, peterwang2050 reviewed
请修改下

2024-03-19 11:27 UTC, peterwang2050 requested changes

2024-03-19 11:27 UTC, peterwang2050 commented on docs/common/dev/_kernel.mdx
> +以 Radxa ZERO 3 为例，可以在开发板上执行 `uname -r` 获取内核名称为 `5.10.160-28-rk356x`。
烧录官方镜像，等系统正常运行后，在开发板上执行

2024-03-19 11:36 UTC, peterwang2050 submitted a review, later dismissed

2024-03-19 12:15 UTC, merged