add m2-install.md、spi-install.md
radxa-docs/documentation pull request #73
Opened 2023-06-07 08:16 UTC by CodeChenL

先别同意pr，等待官方上传5A的spi flash uboot image

2023-06-07 10:37 UTC, Maycides commented
5A SPI flash https://dl.radxa.com/rock5/sw/images/loader/rock-5a/rock-5a-spi-image-g4b32117-20230605.img

2023-06-07 10:37 UTC, Maycides commented
不要重复提交了，在现有基础上改

2023-06-07 10:43 UTC, CodeChenL commented
#64

2023-06-07 11:16 UTC, CodeChenL commented
> 不要重复提交了，在现有基础上改

你的意思是在[/docs/rock5/lowlevel-development/bootloader_spi_flash.md](https://github.com/radxa-docs/documentation/blob/main/docs/rock5/lowlevel-development/bootloader_spi_flash.md)添加5A的用例吗

2023-06-07 11:30 UTC, Maycides commented
是的 5A目前只能线刷SPI flash

2023-06-07 11:32 UTC, CodeChenL commented
> 是的 5A目前只能线刷SPI flash

也可以通过sd卡启动系统来刷吧

2023-06-07 11:36 UTC, RadxaYuntian commented
5A上面SPI和eMMC的引脚是复用的，默认应该没有开启SPI。
如果要从系统内安装应该需要开启对应的overlay才行。

2023-06-07 11:37 UTC, CodeChenL commented
> 

了解了

2023-06-07 12:38 UTC, CodeChenL commented
@Maycides @RadxaYuntian 非常感谢，已完成，可以再次review了

2023-06-08 02:10 UTC, RadxaYuntian requested changes
找了一些基本的问题。感觉之后的文档结构还需要重新调整

2023-06-08 02:10 UTC, RadxaYuntian commented on docs/rock5/lowlevel-development/bootloader_spi_flash.md
> +SPI Nor Flash 存储 bootloader 文件,像 idbloader.img 和 u-boot.itb。
半角逗号

2023-06-08 02:10 UTC, RadxaYuntian commented on docs/rock5/lowlevel-development/bootloader_spi_flash.md
> +ROCK 5B 上有一个 SPI Flash（SPI 闪存）,在 ROCK 5A 上则为与 eMMC 模块复用 B2B 插槽的 SPI Flash 模块，它包含用于备份引导的bootloader，并支持引导其他介质（比如 NVMe、SATA、USB 3），SoC 本身的 maskrom 模式不直接支持这些介质。
`并支持引导其他 SoC 本身不支持启动的介质`

2023-06-08 02:10 UTC, RadxaYuntian commented on docs/rock5/rock5a/getting-started/m2-install.md
> +#such as: sudo xzcat rock-5a-debian-bullseye-xfce4-arm64-20220906-0626-gpt.img.xz  | dd of=/dev/nvme0n1 bs=1M status=progress
`xzcat rock-5a-debian-bullseye-xfce4-arm64-20220906-0626-gpt.img.xz  | sudo dd of=/dev/nvme0n1 bs=1M status=progress`

2023-06-08 02:10 UTC, RadxaYuntian commented on docs/rock5/rock5b/getting-started/m2-install.md
>  sudo sudo xzcat 'your compressed image path' | dd of='your NVME SSD device path' bs=1M status=progress
sudo要在dd前，pipe后就是个新的shell了

2023-06-08 03:48 UTC, CodeChenL commented
基本问题已解决，我也在思考什么样的结构怎么调整

2023-06-09 03:43 UTC, merged